// ╔══════════════════════════════════════════════════════╗
// ║  LOUISE PRO · CURIOSITIES + MILESTONES v2            ║
// ║  ~93 entries bilingual EN/PT covering 0-12 months    ║
// ║                                                      ║
// ║  Structure:                                          ║
// ║    CURIOSITIES: 30 daily (days 1-30)                 ║
// ║    WEEKLY: 48 weekly (weeks 5-52, months 2-12)       ║
// ║    MILESTONES: 11 monthly (months 2-12)              ║
// ║                                                      ║
// ║  Sources: AAP, WHO, NHS, Mayo Clinic, Harvard,       ║
// ║    Stanford, CDC, Zero to Three, NIH, Johns Hopkins  ║
// ║                                                      ║
// ║  Exposes:                                            ║
// ║    window.CURIOSITIES (30 items, by day)             ║
// ║    window.WEEKLY_CURIOSITIES (48 items, by week)     ║
// ║    window.MILESTONES (11 items, by month)            ║
// ╚══════════════════════════════════════════════════════╝

// ──────────────────────────────────────────────────────
//   DAILY CURIOSITIES (days 1-30)
// ──────────────────────────────────────────────────────

window.CURIOSITIES=[
  // Day 1
  {pt:{t:"Bem-vinda ao mundo!",b:"Recem-nascidos enxergam apenas 20-30cm — exatamente a distancia do seu rosto quando ela esta no colo. O mundo dela e preto, branco e tons de cinza, e o rosto dos pais e o objeto favorito. A visao colorida se desenvolve gradualmente nos primeiros meses."},en:{t:"Welcome to the world!",b:"Newborns can only see 20-30cm away — exactly the distance to your face when holding her. Her world is black, white and shades of gray, and parents' faces are her favorite thing. Color vision develops gradually over the first months."}},
  // Day 2
  {pt:{t:"O olfato e o superpoder",b:"Seu bebe reconhece o cheiro da mae desde o primeiro dia — e o sentido mais desenvolvido ao nascer. Estudos mostram que recem-nascidos conseguem identificar o seio materno pelo cheiro e se acalmam quando percebem o perfume natural dos pais. Evite perfumes fortes nos primeiros meses."},en:{t:"Smell is the superpower",b:"Your baby recognizes mom's scent from day one — it's the most developed sense at birth. Studies show newborns can identify the breast by smell alone and calm down when they detect the natural scent of parents. Avoid strong perfumes in the first months."}},
  // Day 3
  {pt:{t:"Reflexos incriveis",b:"O reflexo de preensao palmar e tao forte que um recem-nascido consegue suportar o proprio peso segurando um dedo. Esse reflexo desaparece por volta dos 3-4 meses, quando o movimento consciente comeca a tomar o lugar dos reflexos automaticos herdados dos nossos ancestrais primatas."},en:{t:"Incredible reflexes",b:"The palmar grip reflex is so strong that a newborn could support their own weight holding a finger. This reflex disappears around 3-4 months, when conscious movement starts replacing the automatic reflexes inherited from our primate ancestors."}},
  // Day 4
  {pt:{t:"Sono fragmentado e normal",b:"Bebes dormem 14-17 horas por dia, mas em ciclos curtos de 40-60 minutos — bem menores que os 90 minutos de um adulto. Cerca de 50% desse sono e em fase REM (adultos ficam em 20%), essencial para o desenvolvimento neural. Acordar a cada 2-3h para mamar e biologicamente normal."},en:{t:"Fragmented sleep is normal",b:"Babies sleep 14-17 hours a day, but in short 40-60 minute cycles — much shorter than an adult's 90-minute cycles. About 50% of that sleep is REM (adults are at 20%), essential for neural development. Waking every 2-3h to feed is biologically normal."}},
  // Day 5
  {pt:{t:"O choro e comunicacao",b:"Recem-nascidos tem pelo menos 5 tipos de choro distintos: fome, sono, desconforto, dor e necessidade de contato. Com o tempo, voce vai distinguir cada um. Responder rapidamente ao choro NAO mima — pelo contrario, fortalece o vinculo seguro e reduz estresse a longo prazo."},en:{t:"Crying is communication",b:"Newborns have at least 5 distinct cry types: hunger, sleep, discomfort, pain, and need for contact. Over time, you'll learn to tell them apart. Responding quickly to crying does NOT spoil — on the contrary, it strengthens secure attachment and reduces long-term stress."}},
  // Day 6
  {pt:{t:"Crescimento acelerado do cerebro",b:"O cerebro do bebe forma mais de 1 milhao de conexoes neurais por segundo nos primeiros anos — um ritmo que nunca mais se repete na vida. Aos 3 anos, ela tera quase o dobro de sinapses que um adulto. O cerebro e literalmente esculpido pelas experiencias diarias."},en:{t:"Accelerated brain growth",b:"Baby's brain forms more than 1 million neural connections per second in the first years — a pace that's never repeated in life. By age 3, she'll have nearly twice as many synapses as an adult. The brain is literally sculpted by daily experiences."}},
  // Day 7
  {pt:{t:"O cordao vai cair logo",b:"Entre 7-21 dias o coto do cordao umbilical seca e cai naturalmente. Mantenha limpo e seco, e nunca puxe — pode causar sangramento. Cheiro forte, vermelhidao ao redor ou pus sao sinais para consultar o pediatra. Ate cair, evite banhos de imersao."},en:{t:"The cord will fall soon",b:"Between 7-21 days the umbilical stump dries and falls naturally. Keep it clean and dry, and never pull it — can cause bleeding. Strong smell, redness around it, or pus are signs to call the pediatrician. Until it falls, avoid immersion baths."}},
  // Day 8
  {pt:{t:"Pele a pele e remedio",b:"O contato pele a pele (kangaroo care) regula temperatura, batimentos cardiacos, respiracao e niveis de estresse do bebe — tanto do recem-nascido quanto dos pais. Libera oxitocina (hormonio do amor) em ambos, fortalece o vinculo e ajuda na producao de leite materno."},en:{t:"Skin to skin is medicine",b:"Skin-to-skin contact (kangaroo care) regulates baby's temperature, heart rate, breathing and stress levels — for both newborn and parents. It releases oxytocin (love hormone) in both, strengthens bonding and helps breast milk production."}},
  // Day 9
  {pt:{t:"Ela prefere sua voz",b:"Bebes preferem vozes agudas e melodicas — o chamado parentese. Aquela voz fininha que a gente faz sem pensar? E instinto evolutivo, e funciona: estudos mostram que recem-nascidos acalmam os batimentos quando ouvem a voz da mae, que ja era reconhecida desde o utero."},en:{t:"She prefers your voice",b:"Babies prefer high-pitched, melodic voices — called parentese. That silly high voice we make without thinking? It's an evolutionary instinct, and it works: studies show newborns' heart rates slow when they hear mom's voice, which they already recognized from the womb."}},
  // Day 10
  {pt:{t:"O leite muda de cor e composicao",b:"O leite materno muda durante a mamada (inicio mais aguado, fim mais gorduroso), durante o dia (mais cortisol de manha, mais melatonina a noite) e ate responde a doencas do bebe, aumentando anticorpos especificos. E um fluido vivo e dinamico, impossivel de replicar."},en:{t:"Milk changes color and composition",b:"Breast milk changes during a feed (watery at start, fatty at end), throughout the day (more cortisol in morning, more melatonin at night) and even responds to baby's illness by increasing specific antibodies. It's a living, dynamic fluid — impossible to replicate."}},
  // Day 11
  {pt:{t:"Bebes nascem nadadores",b:"O reflexo de mergulho faz o recem-nascido prender a respiracao automaticamente quando o rosto toca a agua, alem de diminuir o ritmo cardiaco — uma heranca evolutiva. Esse reflexo desaparece por volta dos 6 meses. Mas atencao: isso NAO significa que bebes saibam nadar."},en:{t:"Babies are born swimmers",b:"The diving reflex makes newborns automatically hold their breath when their face touches water, and also slows heart rate — an evolutionary holdover. This reflex disappears around 6 months. But be careful: this does NOT mean babies can swim."}},
  // Day 12
  {pt:{t:"O sorriso esta chegando",b:"Os primeiros sorrisos sao reflexos e aparecem ja no utero ou nos primeiros dias, geralmente durante o sono. O sorriso social verdadeiro — aquele que responde ao seu olhar — chega entre 6-8 semanas e e um dos marcos mais importantes do desenvolvimento emocional."},en:{t:"The smile is coming",b:"First smiles are reflexive and appear even in the womb or first days, usually during sleep. The true social smile — the one that responds to your gaze — arrives between 6-8 weeks and is one of the most important emotional development milestones."}},
  // Day 13
  {pt:{t:"Ela ja sonha!",b:"Bebes passam 50% do sono em fase REM (adultos: 20%), a fase dos sonhos. Ninguem sabe exatamente com o que bebes sonham, mas neurocientistas acreditam que o sono REM ajuda a consolidar a avalanche de aprendizados diarios. A cada cochilo, milhoes de sinapses se reorganizam."},en:{t:"She already dreams!",b:"Babies spend 50% of sleep in REM phase (adults: 20%), the dream phase. Nobody knows exactly what babies dream about, but neuroscientists believe REM sleep helps consolidate the avalanche of daily learning. With every nap, millions of synapses reorganize."}},
  // Day 14
  {pt:{t:"Recuperou o peso!",b:"Bebes perdem 5-10% do peso nos primeiros dias (liberacao de fluidos) e geralmente recuperam ate o dia 10-14. Depois, ganham cerca de 20-30g por dia no primeiro mes — quase 1kg por mes. E um dos periodos de maior velocidade de crescimento na vida humana."},en:{t:"Weight recovered!",b:"Babies lose 5-10% of birth weight in the first days (fluid release) and usually regain it by day 10-14. After that, they gain about 20-30g per day in the first month — almost 1kg per month. It's one of the fastest growth periods in human life."}},
  // Day 15
  {pt:{t:"Imitacao precoce",b:"Recem-nascidos de apenas algumas semanas ja conseguem imitar expressoes faciais simples. Se voce mostrar a lingua bem devagar, ela pode tentar copiar. Essa imitacao precoce e controlada por neuronios-espelho, e e a base neurologica da empatia e do aprendizado social."},en:{t:"Early imitation",b:"Newborns just a few weeks old can imitate simple facial expressions. If you slowly stick out your tongue, she may try to copy. This early imitation is controlled by mirror neurons, and is the neurological basis of empathy and social learning."}},
  // Day 16
  {pt:{t:"Ruido branco acalma",b:"Sons como secador, aspirador, chuveiro ou 'shhhh' imitam o ambiente dentro do utero — que, ao contrario do que muitos pensam, e barulhento (~85 decibeis!). E por isso que bebes se acalmam com esses sons: eles lembram o refugio sonoro dos 9 meses de gestacao."},en:{t:"White noise soothes",b:"Sounds like hair dryers, vacuums, showers or 'shhhh' mimic the womb environment — which, contrary to popular belief, is noisy (~85 decibels!). That's why babies calm down with these sounds: they remind her of the sonic refuge of 9 months of gestation."}},
  // Day 17
  {pt:{t:"A fontanela pulsa",b:"A moleira do bebe (fontanela) pulsa com os batimentos cardiacos — e e totalmente normal. Ela existe para permitir que o cranio se molde durante o parto e continue crescendo nos primeiros anos. A fontanela anterior fecha entre 9-18 meses, a posterior ate os 2 meses."},en:{t:"The fontanelle pulses",b:"The baby's soft spot (fontanelle) pulses with the heartbeat — and it's completely normal. It exists to allow the skull to mold during birth and keep growing in the first years. The anterior fontanelle closes between 9-18 months, the posterior one by 2 months."}},
  // Day 18
  {pt:{t:"Choro sem lagrimas",b:"Recem-nascidos choram sem lagrimas ate 3-4 semanas de vida — as glandulas lacrimais produzem apenas o suficiente para lubrificar os olhos. As primeiras lagrimas visiveis aparecem entre 1-3 meses, e muitos pais se surpreendem com esse momento (emocionante e levemente triste)."},en:{t:"Tearless crying",b:"Newborns cry without tears until 3-4 weeks of life — tear glands only produce enough to lubricate the eyes. The first visible tears appear between 1-3 months, and many parents are surprised by this moment (touching and slightly sad)."}},
  // Day 19
  {pt:{t:"O toque constroi o cerebro",b:"Cada carinho, abraco e contato fisico forma novas conexoes neurais no cerebro do bebe. A massagem infantil, em particular, reduz cortisol (estresse), melhora o sono e fortalece o sistema imune. O toque nao e so afetivo — e nutricao neurologica essencial."},en:{t:"Touch builds the brain",b:"Every caress, hug and physical contact forms new neural connections in baby's brain. Infant massage, in particular, reduces cortisol (stress), improves sleep and strengthens the immune system. Touch isn't just emotional — it's essential neurological nutrition."}},
  // Day 20
  {pt:{t:"Ela ouve todas as linguas",b:"Ate os 6 meses, bebes conseguem distinguir fonemas de TODAS as linguas humanas — inclusive sons que os pais nao conseguem mais diferenciar. Um bebe japones, por exemplo, distingue /l/ e /r/ ate os 6 meses. Depois, o cerebro comeca a 'especializar' na lingua materna."},en:{t:"She hears every language",b:"Until 6 months, babies can distinguish phonemes from ALL human languages — including sounds that parents can no longer differentiate. A Japanese baby, for example, can tell /l/ and /r/ apart until 6 months. After that, the brain starts 'specializing' in the native language."}},
  // Day 21
  {pt:{t:"Padrao de sono em formacao",b:"Ate 8-12 semanas, o ritmo circadiano (relogio biologico) e fraco ou inexistente. E por isso que recem-nascidos confundem dia e noite. Exposicao a luz natural durante o dia e escuridao a noite ajuda a formar esse ciclo — e um dos trabalhos mais importantes dos primeiros meses."},en:{t:"Sleep pattern forming",b:"Until 8-12 weeks, the circadian rhythm (biological clock) is weak or non-existent. That's why newborns confuse day and night. Natural light exposure during the day and darkness at night help form this cycle — one of the most important tasks of the first months."}},
  // Day 22
  {pt:{t:"O estomago e minusculo",b:"O estomago do recem-nascido tem capacidade de uma cereja no dia 1 (5-7ml), uma noz no dia 3 (22-27ml) e um ovo no dia 10 (60-80ml). E por isso que ela mama pouco e frequentemente — e perfeitamente normal. Mamadas a cada 2-3h sao esperadas nos primeiros meses."},en:{t:"The stomach is tiny",b:"A newborn's stomach holds about a cherry on day 1 (5-7ml), a walnut by day 3 (22-27ml), and an egg by day 10 (60-80ml). That's why she feeds small and often — it's perfectly normal. Feeds every 2-3h are expected in the first months."}},
  // Day 23
  {pt:{t:"Preferencia por contrastes",b:"Bebes preferem olhar para padroes de alto contraste — listras preto e branco sao mais interessantes que cores suaves. Isso acontece porque o cortex visual ainda esta amadurecendo. Livros e brinquedos em preto, branco e vermelho sao ideais para estimular os primeiros meses."},en:{t:"Preference for contrasts",b:"Babies prefer looking at high-contrast patterns — black and white stripes are more interesting than soft colors. This is because the visual cortex is still maturing. Books and toys in black, white and red are ideal for stimulating the first months."}},
  // Day 24
  {pt:{t:"A voz do pai tambem acalma",b:"Estudos mostram que a voz grave do pai tem efeito calmante comparavel a voz da mae — e bebes reconhecem ambas desde o utero. Conversar, cantar e ler para o bebe, mesmo recem-nascido, estimula o desenvolvimento da linguagem e fortalece o vinculo afetivo com ambos os pais."},en:{t:"Dad's voice calms too",b:"Studies show that dad's deep voice has a calming effect comparable to mom's — and babies recognize both from the womb. Talking, singing and reading to baby, even as a newborn, stimulates language development and strengthens emotional bonds with both parents."}},
  // Day 25
  {pt:{t:"Reflexo de Moro (susto)",b:"O movimento de 'susto' — quando o bebe abre bracos e pernas de repente — se chama reflexo de Moro, uma heranca evolutiva. Desaparece entre 4-6 meses. O swaddle (enrolar como charuto) imita o aperto do utero e reduz esses sustos, ajudando o bebe a dormir mais profundamente."},en:{t:"Moro reflex (startle)",b:"The 'startle' movement — when baby suddenly spreads arms and legs — is called the Moro reflex, an evolutionary holdover. It disappears between 4-6 months. Swaddling (wrapping snugly) mimics the womb's hold and reduces these startles, helping baby sleep more soundly."}},
  // Day 26
  {pt:{t:"Ela esta estudando seu rosto",b:"Com 3-4 semanas, bebes focam melhor em objetos a 20-30cm — exatamente a distancia do seu rosto durante a amamentacao. Ela nao esta so olhando, esta ESTUDANDO cada detalhe: seu queixo, seus olhos, o movimento da sua boca. E como ela aprende a reconhecer voces."},en:{t:"She's studying your face",b:"At 3-4 weeks, babies focus best on objects 20-30cm away — exactly the distance to your face during feeding. She's not just looking, she's STUDYING every detail: your chin, your eyes, your mouth movements. That's how she learns to recognize you."}},
  // Day 27
  {pt:{t:"O intestino esta aprendendo",b:"Colicas sao comuns entre 2-12 semanas. O sistema digestivo ainda esta amadurecendo, a microbiota intestinal esta se formando e o bebe ainda aprende a processar bolhas de ar. Geralmente passam por volta do 3o mes. Massagem na barriga e posicao de bruco no colo ajudam."},en:{t:"The gut is learning",b:"Colic is common between 2-12 weeks. The digestive system is still maturing, gut microbiota is forming, and baby is still learning to process air bubbles. It usually passes around month 3. Belly massage and tummy-down position on your lap help."}},
  // Day 28
  {pt:{t:"Quase 1 mes!",b:"Em 4 semanas, o cerebro cresceu cerca de 15% e ja formou trilhoes de novas sinapses. Louise ja reconhece sua voz entre outras, prefere seu rosto a qualquer outro, e comeca a seguir objetos lentamente com os olhos. A transformacao diaria e surpreendente."},en:{t:"Almost 1 month!",b:"In 4 weeks, the brain has grown about 15% and formed trillions of new synapses. Louise already recognizes your voice among others, prefers your face to any other, and starts slowly following objects with her eyes. The daily transformation is astonishing."}},
  // Day 29
  {pt:{t:"Musculos do pescoco",b:"O bebe ja comeca a tentar erguer brevemente a cabeca durante o tummy time (barriga pra baixo). Cada segundo fortalece os musculos do pescoco, ombros e costas — essenciais para rolar, sentar e engatinhar depois. Alguns minutos por dia, 3-4 vezes, e o ideal."},en:{t:"Neck muscles",b:"Baby is starting to briefly lift her head during tummy time (belly down). Every second strengthens neck, shoulder and back muscles — essential for rolling, sitting and crawling later. A few minutes per day, 3-4 times, is ideal."}},
  // Day 30
  {pt:{t:"1 mes completo! 🎉",b:"Parabens! Em 30 dias, Louise cresceu 3-4cm, ganhou cerca de 700-900g e passou pelo periodo mais intenso da vida humana. Voces tambem cresceram muito — como pais, como casal, como familia. O pior (e mais confuso) esta passando. Se orgulhem: vao bem demais."},en:{t:"1 month complete! 🎉",b:"Congratulations! In 30 days, Louise grew 3-4cm, gained about 700-900g and went through the most intense period of human life. You grew a lot too — as parents, as a couple, as a family. The hardest (and most confusing) part is passing. Be proud: you're doing amazing."}},
];

// ──────────────────────────────────────────────────────
//   WEEKLY CURIOSITIES (weeks 5-52)
//   Index 0 = week 5, index 47 = week 52
// ──────────────────────────────────────────────────────

window.WEEKLY_CURIOSITIES=[
  // Week 5
  {pt:{t:"Choro no pico",b:"O choro dos bebes atinge seu pico por volta das 6 semanas. E chamado de 'periodo do choro roxo' (PURPLE crying) e e completamente normal. Passa por volta dos 3-4 meses. Nao e birra, nao e culpa sua — e uma fase neurologica. Se precisar de uma pausa, coloque o bebe no berco e respire."},en:{t:"Crying at its peak",b:"Baby crying peaks around 6 weeks. It's called the 'PURPLE crying period' and is completely normal. It passes around 3-4 months. It's not a tantrum, not your fault — it's a neurological phase. If you need a break, put baby in the crib and breathe."}},
  // Week 6
  {pt:{t:"O sorriso social chegou!",b:"Entre 6-8 semanas, aparece o sorriso social: aquele que responde ao seu rosto, nao e reflexo. E considerado um dos marcos mais importantes do desenvolvimento emocional. Pela primeira vez, Louise esta se comunicando intencionalmente. Anote o dia — esse momento nao volta."},en:{t:"The social smile is here!",b:"Between 6-8 weeks, the social smile appears: the one that responds to your face, not a reflex. It's considered one of the most important emotional development milestones. For the first time, Louise is communicating intentionally. Mark the day — this moment doesn't come back."}},
  // Week 7
  {pt:{t:"Cocos e arrulhos",b:"Depois do sorriso, chegam os primeiros sons vocais intencionais: 'ahh', 'ooo', 'goo'. E o estagio do arrulho (cooing), que antecede o balbucio. Responda aos sons como se fosse uma conversa real — essa troca 'serve-and-return' e fundamental para o desenvolvimento da linguagem."},en:{t:"Coos and gurgles",b:"After the smile come the first intentional vocal sounds: 'ahh', 'ooo', 'goo'. This is the cooing stage, which precedes babbling. Respond to the sounds as if it were a real conversation — this 'serve-and-return' exchange is fundamental for language development."}},
  // Week 8
  {pt:{t:"Ritmo circadiano emergindo",b:"Por volta das 8-9 semanas, o bebe comeca a produzir seu proprio cortisol e melatonina em ritmo circadiano. E agora que noites comecam a ficar mais longas (as vezes) e dias mais acordados. Exposicao a luz natural de manha ajuda muito esse processo."},en:{t:"Circadian rhythm emerging",b:"Around 8-9 weeks, baby starts producing her own cortisol and melatonin in a circadian rhythm. This is when nights start getting longer (sometimes) and days more alert. Natural morning light exposure helps this process a lot."}},
  // Week 9
  {pt:{t:"Descobrindo as maos",b:"Por volta de 2 meses, Louise comeca a 'descobrir' as proprias maos. Ela passa minutos olhando para elas, abrindo e fechando os dedos, fascinada. E um marco cognitivo importante: ela esta comecando a entender que aquelas maos sao DELA, e que ela pode controla-las."},en:{t:"Discovering the hands",b:"Around 2 months, Louise starts 'discovering' her own hands. She spends minutes staring at them, opening and closing her fingers, fascinated. It's an important cognitive milestone: she's starting to understand those hands are HERS, and that she can control them."}},
  // Week 10
  {pt:{t:"Controle da cabeca",b:"Por volta de 2-3 meses, o controle da cabeca melhora dramaticamente. Quando no colo, Louise ja consegue sustentar a cabeca por alguns segundos. E pre-requisito para sentar, e depende de tummy time consistente — mesmo que ela reclame no comeco."},en:{t:"Head control",b:"Around 2-3 months, head control improves dramatically. When held upright, Louise can support her head for a few seconds. It's a prerequisite for sitting, and depends on consistent tummy time — even if she complains at first."}},
  // Week 11
  {pt:{t:"Colicas podem diminuir",b:"Entre 10-12 semanas, as colicas geralmente comecam a ceder. O sistema digestivo amadurece, a microbiota se estabelece, e o bebe aprende a processar gases. Se passou pelo periodo mais dificil, saiba: a partir daqui, muita coisa comeca a melhorar."},en:{t:"Colic may ease",b:"Between 10-12 weeks, colic usually starts to ease. The digestive system matures, gut microbiota stabilizes, and baby learns to process gas. If you've been through the hardest period, know this: from here, many things start to get better."}},
  // Week 12
  {pt:{t:"3 meses! Gargalhadas",b:"Por volta de 3-4 meses chega uma das experiencias mais magicas: a primeira gargalhada. E imprevisivel — pode ser uma lambida do cachorro, um barulho engracado, ou simplesmente seu rosto. Grave em video: nao vai se arrepender."},en:{t:"3 months! Giggles",b:"Around 3-4 months comes one of the most magical experiences: the first giggle. It's unpredictable — could be a dog's lick, a funny noise, or simply your face. Record it on video: you won't regret it."}},
  // Week 13
  {pt:{t:"Seguindo objetos",b:"Por volta de 3 meses, Louise comeca a seguir objetos em movimento com os olhos de forma fluida — antes era mais lento e intermitente. Ela tambem passa a orientar a cabeca na direcao de sons. E uma explosao de consciencia visual e auditiva."},en:{t:"Tracking objects",b:"Around 3 months, Louise starts smoothly tracking moving objects with her eyes — before it was slower and more intermittent. She also begins turning her head toward sounds. It's an explosion of visual and auditory awareness."}},
  // Week 14
  {pt:{t:"Cores chegando",b:"A visao colorida amadurece por volta de 3-4 meses. Antes, ela via principalmente contrastes; agora comeca a distinguir vermelhos, azuis e amarelos. Brinquedos coloridos ficam muito mais interessantes. Essa explosao visual acelera o desenvolvimento cognitivo."},en:{t:"Colors arriving",b:"Color vision matures around 3-4 months. Before, she mostly saw contrasts; now she starts distinguishing reds, blues and yellows. Colorful toys become much more interesting. This visual explosion accelerates cognitive development."}},
  // Week 15
  {pt:{t:"Pegando objetos",b:"Entre 3-4 meses, Louise comeca a pegar objetos intencionalmente — antes eram reflexos. Os primeiros alvos: seu cabelo, seus oculos, brinquedos pendurados. E um grande salto de coordenacao viso-motora. Atencao: tudo vai direto pra boca."},en:{t:"Grabbing objects",b:"Between 3-4 months, Louise starts intentionally grabbing objects — before, these were reflexes. First targets: your hair, your glasses, hanging toys. It's a big leap in visual-motor coordination. Warning: everything goes straight to the mouth."}},
  // Week 16
  {pt:{t:"4 meses: salto cognitivo",b:"Entre 3-4 meses ha uma maturacao drastica do sistema nervoso. Ela ri, balbucia, vocaliza, reconhece voces, segue voce com os olhos pelo quarto. Os ciclos de sono comecam a se organizar em estagios mais adultos — mas isso pode temporariamente bagunçar o sono."},en:{t:"4 months: cognitive leap",b:"Between 3-4 months there's a dramatic maturation of the nervous system. She laughs, babbles, vocalizes, recognizes voices, follows you around the room with her eyes. Sleep cycles begin organizing into more adult-like stages — but this can temporarily disrupt sleep."}},
  // Week 17
  {pt:{t:"A 'regressao' dos 4 meses",b:"Muitos pais notam o sono piorando em torno dos 4 meses. Nao e 'regressao' — e PROGRESSO: o sono esta amadurecendo para ciclos mais adultos (50-60 minutos) e a Louise acorda mais facil entre eles. Passa em algumas semanas quando ela aprende a reconectar ciclos."},en:{t:"The 4-month 'regression'",b:"Many parents notice sleep getting worse around 4 months. It's not 'regression' — it's PROGRESS: sleep is maturing into more adult-like cycles (50-60 min) and Louise wakes more easily between them. It passes in a few weeks as she learns to reconnect cycles."}},
  // Week 18
  {pt:{t:"Comecando a rolar",b:"Entre 4-5 meses, muitos bebes comecam a rolar de bruco para costas (mais facil, precisa so de um impulso). De costas para bruco leva mais tempo — geralmente 5-7 meses — porque exige mais forca de tronco. Nunca deixe ela desacompanhada em superficies altas."},en:{t:"Starting to roll",b:"Between 4-5 months, many babies start rolling from tummy to back (easier, needs just a push). Back to tummy takes longer — usually 5-7 months — because it requires more core strength. Never leave her alone on high surfaces."}},
  // Week 19
  {pt:{t:"Balbucio comeca",b:"Por volta de 4-5 meses, os sons vocais ganham consoantes: 'ba', 'da', 'ma'. E o inicio do balbucio — uma etapa crucial da linguagem. Responda sempre, imite os sons de volta. Esse 'bate-papo' acelera o desenvolvimento da fala mais do que qualquer brinquedo educativo."},en:{t:"Babbling begins",b:"Around 4-5 months, vocal sounds gain consonants: 'ba', 'da', 'ma'. This is the start of babbling — a crucial language stage. Always respond, imitate the sounds back. This 'chat' accelerates speech development more than any educational toy."}},
  // Week 20
  {pt:{t:"Pode tentar alcancar",b:"Por volta de 5 meses, Louise ja alcanca objetos com intencao e precisao. Ela olha, planeja, move o braco, pega. E um dos primeiros sinais de 'intencionalidade' — um marco cognitivo fundamental que mostra planejamento motor consciente."},en:{t:"Intentional reaching",b:"Around 5 months, Louise reaches for objects with intention and precision. She looks, plans, moves her arm, grabs. It's one of the first signs of 'intentionality' — a fundamental cognitive milestone showing conscious motor planning."}},
  // Week 21
  {pt:{t:"Risadas altas",b:"As risadas ficam mais frequentes e mais altas. Louise comeca a rir em antecipacao (antes mesmo da brincadeira acontecer), o que mostra memoria de curto prazo e expectativa. Ela esta aprendendo que certas situacoes levam a coisas engracadas."},en:{t:"Loud laughs",b:"Laughter becomes more frequent and louder. Louise starts laughing in anticipation (before the game even happens), showing short-term memory and expectation. She's learning that certain situations lead to funny things."}},
  // Week 22
  {pt:{t:"Passando objetos",b:"Por volta de 5-6 meses, Louise aprende a passar objetos de uma mao para outra. E uma grande conquista de coordenacao bilateral — os dois lados do cerebro comecam a trabalhar juntos de forma coordenada. Brinquedos leves e faceis de segurar ajudam."},en:{t:"Passing objects",b:"Around 5-6 months, Louise learns to pass objects from one hand to the other. It's a major bilateral coordination achievement — both sides of the brain start working together coordinately. Light, easy-to-hold toys help."}},
  // Week 23
  {pt:{t:"Reconhecimento de nome",b:"Por volta de 5-6 meses, bebes comecam a reconhecer o proprio nome — voltam a cabeca quando voce chama. E um marco cognitivo importante: ela entende que 'Louise' se refere a ELA. Use o nome dela com frequencia em contextos afetivos."},en:{t:"Name recognition",b:"Around 5-6 months, babies start recognizing their own name — turning their head when called. It's an important cognitive milestone: she understands 'Louise' refers to HER. Use her name frequently in affectionate contexts."}},
  // Week 24
  {pt:{t:"Pronta para solidos?",b:"Por volta de 6 meses, Louise pode estar pronta para alimentos solidos. Sinais: sustenta a cabeca, senta com apoio, mostra interesse pela comida, abre a boca quando oferecem, perdeu o reflexo de empurrar comida com a lingua. O leite ainda e a base, mas o mundo de sabores esta abrindo."},en:{t:"Ready for solids?",b:"Around 6 months, Louise may be ready for solid foods. Signs: holds head up, sits with support, shows interest in food, opens mouth when offered, lost tongue-thrust reflex. Milk is still the base, but a world of flavors is opening up."}},
  // Week 25
  {pt:{t:"6 meses! Janela critica",b:"Aos 6 meses, o leite materno ja nao supre todas as necessidades — especialmente ferro e zinco. E por isso que essa e a janela ideal para introduzir solidos. Ofereca variedade desde o inicio: paladares expostos agora sao mais aceitos depois."},en:{t:"6 months! Critical window",b:"At 6 months, breast milk alone no longer meets all needs — especially iron and zinc. That's why this is the ideal window to introduce solids. Offer variety from the start: flavors exposed now are more accepted later."}},
  // Week 26
  {pt:{t:"Aversao a estranhos comeca",b:"Por volta de 6-8 meses, pode surgir a ansiedade de estranhos. Louise pode chorar com pessoas que antes adorava — inclusive avos e tios. NAO e falta de carinho, e um sinal de que o vinculo com voces esta MUITO forte. Passa com o tempo e com exposicao gradual."},en:{t:"Stranger wariness begins",b:"Around 6-8 months, stranger anxiety may emerge. Louise may cry with people she used to love — including grandparents and aunts. This is NOT lack of affection, it's a sign that her bond with you is VERY strong. It passes with time and gradual exposure."}},
  // Week 27
  {pt:{t:"Permanencia do objeto",b:"Por volta de 6-8 meses, Louise comeca a entender que objetos continuam existindo mesmo quando fora de vista — o conceito de permanencia do objeto. E por isso que peek-a-boo (achou!) fica subitamente tao divertido. E uma das bases da memoria de trabalho."},en:{t:"Object permanence",b:"Around 6-8 months, Louise starts understanding that objects continue existing even when out of sight — the concept of object permanence. That's why peek-a-boo suddenly becomes so fun. It's one of the foundations of working memory."}},
  // Week 28
  {pt:{t:"Sentando sem apoio",b:"Por volta de 7 meses, muitos bebes comecam a sentar sem apoio por alguns segundos. Isso libera as maos para explorar objetos de angulos novos — o que, nao por coincidencia, acelera o desenvolvimento da permanencia do objeto e da cognicao espacial."},en:{t:"Sitting without support",b:"Around 7 months, many babies start sitting without support for a few seconds. This frees the hands to explore objects from new angles — which, not by coincidence, accelerates object permanence and spatial cognition development."}},
  // Week 29
  {pt:{t:"Balbucio com consoantes",b:"Por volta de 6-7 meses, o balbucio fica mais complexo: 'ba-ba-ba', 'ma-ma-ma', 'da-da-da'. Ela ainda nao associa essas silabas a pessoas, mas esta treinando a musculatura da fala. E um dos momentos mais adoraveis do desenvolvimento da linguagem."},en:{t:"Babbling with consonants",b:"Around 6-7 months, babbling gets more complex: 'ba-ba-ba', 'ma-ma-ma', 'da-da-da'. She doesn't yet associate these syllables with people, but she's training her speech muscles. It's one of the most adorable language development moments."}},
  // Week 30
  {pt:{t:"Aprendendo causa e efeito",b:"Por volta de 7 meses, Louise comeca a entender causa e efeito: se ela joga o brinquedo, ele cai. Se ela bate numa superficie, faz barulho. E por isso que bebes nessa idade ADORAM derrubar coisas repetidamente — nao e provocacao, e ciencia."},en:{t:"Learning cause and effect",b:"Around 7 months, Louise starts understanding cause and effect: if she drops a toy, it falls. If she bangs a surface, it makes noise. That's why babies at this age LOVE dropping things repeatedly — it's not provocation, it's science."}},
  // Week 31
  {pt:{t:"Comecando a se mover",b:"Entre 7-9 meses, as formas de locomocao comecam: rolar continuo, arrastar-se de bruco (commando crawl), sentar e girar, ou engatinhar classico. Algumas nunca engatinham — pulam direto para ficar de pe. Todos os caminhos sao normais."},en:{t:"Starting to move",b:"Between 7-9 months, ways of moving emerge: continuous rolling, commando crawling on belly, sitting and pivoting, or classic crawling. Some babies never crawl — they skip straight to standing. All paths are normal."}},
  // Week 32
  {pt:{t:"Dentes chegando",b:"Os primeiros dentes geralmente aparecem entre 6-10 meses, comecando pelos incisivos inferiores. Sinais: baba excessiva, gengivas inchadas, necessidade de morder tudo, irritabilidade, sono bagunçado. Mordedores gelados e gengivas massageadas ajudam bastante."},en:{t:"Teeth arriving",b:"First teeth usually appear between 6-10 months, starting with lower incisors. Signs: excessive drool, swollen gums, need to bite everything, irritability, disrupted sleep. Cold teething rings and gum massage help a lot."}},
  // Week 33
  {pt:{t:"Ansiedade de separacao",b:"Entre 8-10 meses, Louise pode comecar a chorar quando voce sai do quarto — mesmo por segundos. E um sinal de que ela ja entende permanencia (voce ainda existe, mas nao esta visivel) E de que ela valoriza sua presenca. Passa por volta dos 18-24 meses."},en:{t:"Separation anxiety",b:"Between 8-10 months, Louise may cry when you leave the room — even for seconds. It's a sign she already understands permanence (you still exist, but aren't visible) AND that she values your presence. It passes around 18-24 months."}},
  // Week 34
  {pt:{t:"Imitacao complexa",b:"Por volta de 8-9 meses, Louise comeca a imitar comportamentos mais complexos: bater palmas, dar tchau, levar um telefone imaginario ao ouvido, fingir tomar um golinho. E o inicio do pensamento simbolico — a base da imaginacao e da linguagem."},en:{t:"Complex imitation",b:"Around 8-9 months, Louise starts imitating more complex behaviors: clapping, waving goodbye, bringing an imaginary phone to her ear, pretending to sip. It's the start of symbolic thinking — the foundation of imagination and language."}},
  // Week 35
  {pt:{t:"Apontando com o dedo",b:"Por volta de 9 meses, muitos bebes comecam a apontar — primeiro com a mao inteira, depois com o indicador. Apontar e um grande marco comunicativo: e a primeira forma de compartilhar atencao sobre algo. Estudos mostram que apontar prediz vocabulario futuro."},en:{t:"Pointing",b:"Around 9 months, many babies start pointing — first with the whole hand, then with the index finger. Pointing is a major communicative milestone: it's the first form of shared attention about something. Studies show pointing predicts future vocabulary."}},
  // Week 36
  {pt:{t:"9 meses: exploradora",b:"Aos 9 meses, Louise pode estar engatinhando, arrastando-se ou tentando se puxar para ficar de pe. O mundo ficou literalmente maior. E hora de reforcar a seguranca da casa: tomadas, quinas de moveis, produtos quimicos, escadas. Ela vai encontrar TUDO."},en:{t:"9 months: explorer",b:"At 9 months, Louise may be crawling, scooting, or trying to pull up to stand. The world literally got bigger. Time to baby-proof the house: outlets, furniture corners, chemicals, stairs. She WILL find everything."}},
  // Week 37
  {pt:{t:"Pinca imatura",b:"Por volta de 8-10 meses, Louise desenvolve a pinca imatura: usa polegar e o lado do indicador para pegar objetos pequenos. Isso prepara para a pinca fina (pontas dos dedos), que vem aos 11-12 meses e e essencial para comer sozinha."},en:{t:"Immature pincer",b:"Around 8-10 months, Louise develops the immature pincer grasp: uses thumb and side of index finger to grab small objects. This prepares for the fine pincer (fingertips), which comes at 11-12 months and is essential for self-feeding."}},
  // Week 38
  {pt:{t:"Entende o 'nao'",b:"Por volta de 9-10 meses, Louise comeca a entender o 'nao'. Ela pode parar (brevemente) e olhar pra voce. Isso NAO significa obedecer — significa que ela reconhece a palavra e seu tom. A obediencia vem muito mais tarde, com o amadurecimento do controle inibitorio."},en:{t:"Understands 'no'",b:"Around 9-10 months, Louise starts understanding 'no'. She may stop (briefly) and look at you. This does NOT mean obeying — it means she recognizes the word and your tone. Obedience comes much later, with the maturation of inhibitory control."}},
  // Week 39
  {pt:{t:"Memoria aumenta",b:"Por volta de 9-10 meses, a memoria de trabalho da uma saltou. Ela lembra onde objetos estao escondidos, reconhece rotinas diarias e consegue antecipar eventos (por exemplo: fica animada quando voce pega a mamadeira). E um dos marcos cognitivos mais importantes do ano."},en:{t:"Memory grows",b:"Around 9-10 months, working memory takes a big leap. She remembers where objects are hidden, recognizes daily routines and can anticipate events (for example: getting excited when you grab the bottle). It's one of the most important cognitive milestones of the year."}},
  // Week 40
  {pt:{t:"Comidas com as maos",b:"Por volta de 9-10 meses, Louise pode comecar a se alimentar sozinha com as maos (baby-led weaning ou finger foods). Sim, vai fazer muita bagunça. Sim, vale a pena: ela aprende texturas, tamanhos, auto-regulacao de apetite e independencia. Tudo em uma so refeicao."},en:{t:"Finger foods",b:"Around 9-10 months, Louise may start self-feeding with her hands (baby-led weaning or finger foods). Yes, it'll be messy. Yes, it's worth it: she learns textures, sizes, appetite self-regulation and independence. All in one meal."}},
  // Week 41
  {pt:{t:"Puxando para ficar de pe",b:"Entre 9-11 meses, muitos bebes comecam a se puxar para ficar de pe, usando moveis como apoio. Depois vem o 'cruising' — andar de lado segurando em moveis. E a transicao final antes dos primeiros passos independentes."},en:{t:"Pulling up to stand",b:"Between 9-11 months, many babies start pulling up to stand using furniture for support. Then comes 'cruising' — walking sideways holding onto furniture. It's the final transition before first independent steps."}},
  // Week 42
  {pt:{t:"Primeiras palavras?",b:"Por volta de 10-12 meses, podem aparecer as primeiras palavras: 'mama', 'papa', 'oi', 'nao', nomes de brinquedos ou pets. Nem sempre sao claras. Nem sempre vem no tempo medio — algumas saem antes, outras depois. O que importa e que ela entenda e tente se comunicar."},en:{t:"First words?",b:"Around 10-12 months, first words may appear: 'mama', 'dada', 'hi', 'no', names of toys or pets. Not always clear. Not always on the average timeline — some come earlier, others later. What matters is that she understands and tries to communicate."}},
  // Week 43
  {pt:{t:"Preferencias fortes",b:"Por volta de 10-11 meses, a personalidade comeca a aparecer com forca. Louise ja tem comidas favoritas, brinquedos preferidos, pessoas com quem se sente mais segura. Ela pode recusar objetos ou situacoes que antes aceitava. Isso e amadurecimento, nao birra."},en:{t:"Strong preferences",b:"Around 10-11 months, personality starts emerging strongly. Louise has favorite foods, preferred toys, people she feels safest with. She may refuse objects or situations she used to accept. This is maturation, not tantrum."}},
  // Week 44
  {pt:{t:"Dando tchau",b:"Por volta de 10-11 meses, Louise aprende gestos comunicativos: dar tchau, bater palmas, estender os bracos para ser pega, balancar a cabeca para 'nao'. Esses gestos sao precursores da linguagem e mostram que ela esta se comunicando intencionalmente."},en:{t:"Waving goodbye",b:"Around 10-11 months, Louise learns communicative gestures: waving goodbye, clapping, reaching arms to be picked up, shaking head for 'no'. These gestures are precursors to language and show she's communicating intentionally."}},
  // Week 45
  {pt:{t:"Pinca fina",b:"Por volta de 11-12 meses, a pinca fina se desenvolve: polegar e indicador se tocam nas pontas para pegar objetos minusculos (como um grao de feijao). E um pre-requisito para usar talheres, escrever e tocar instrumentos. Ofereca oportunidades seguras de pratica."},en:{t:"Fine pincer grasp",b:"Around 11-12 months, the fine pincer grasp develops: thumb and index finger touch at the tips to pick up tiny objects (like a bean). It's a prerequisite for using utensils, writing, and playing instruments. Offer safe practice opportunities."}},
  // Week 46
  {pt:{t:"Primeiros passos possiveis",b:"Entre 9-15 meses, alguns bebes comecam a dar os primeiros passos independentes. A maioria anda entre 12-14 meses. Os primeiros passos sao desajeitados, com bracos no alto e pernas afastadas — e absolutamente normal. Ela vai cair MUITAS vezes antes de dominar."},en:{t:"First steps possible",b:"Between 9-15 months, some babies take their first independent steps. Most walk between 12-14 months. First steps are clumsy, arms up and legs spread wide — totally normal. She'll fall MANY times before mastering it."}},
  // Week 47
  {pt:{t:"Compreendendo comandos",b:"Por volta de 11-12 meses, Louise comeca a entender comandos simples: 'da pra mamae', 'cade o nariz', 'pega a bola'. A compreensao (linguagem receptiva) vem sempre antes da fala (linguagem expressiva) — ela entende muito mais do que consegue expressar."},en:{t:"Understanding commands",b:"Around 11-12 months, Louise starts understanding simple commands: 'give to mama', 'where's the nose', 'get the ball'. Understanding (receptive language) always comes before speech (expressive language) — she understands much more than she can express."}},
  // Week 48
  {pt:{t:"Explorando tudo",b:"Perto de 1 ano, Louise e uma pequena cientista: ela enfia tudo na boca, joga objetos, bate, empilha, derruba. Cada uma dessas acoes e uma experiencia para entender o mundo. Resistir ao impulso de parar essas exploracoes ajuda muito no desenvolvimento."},en:{t:"Exploring everything",b:"Near 1 year, Louise is a little scientist: she puts everything in her mouth, throws objects, bangs, stacks, drops. Each of these actions is an experiment to understand the world. Resisting the urge to stop these explorations helps a lot in development."}},
  // Week 49
  {pt:{t:"Objetos de apego",b:"Por volta de 10-12 meses, muitos bebes desenvolvem apego a um objeto especial — paninho, pelucia, chupeta. E um 'objeto transicional' e ajuda a lidar com separacoes e mudancas. E saudavel e comum. Nao force a retirada desse apego antes da hora."},en:{t:"Attachment objects",b:"Around 10-12 months, many babies develop attachment to a special object — blankie, plushie, pacifier. It's a 'transitional object' and helps deal with separations and changes. It's healthy and common. Don't force removal of this attachment too early."}},
  // Week 50
  {pt:{t:"Linguagem explosao",b:"Embora as primeiras palavras venham por volta de 1 ano, a compreensao explode antes. Estudos mostram que aos 10-12 meses, bebes ja entendem cerca de 50-100 palavras — mesmo que so digam 1 ou 2. Continue conversando, lendo, narrando o dia — ela esta absorvendo tudo."},en:{t:"Language explosion",b:"Although first words come around 1 year, understanding explodes before. Studies show that at 10-12 months, babies already understand about 50-100 words — even if they only say 1 or 2. Keep talking, reading, narrating the day — she's absorbing everything."}},
  // Week 51
  {pt:{t:"Quase 1 ano!",b:"Perto de completar 1 ano, Louise ja percorreu um caminho incrivel: de recem-nascida indefesa a pequena exploradora com personalidade, preferencias, comunicacao e apego. Em 52 semanas, o cerebro dela formou trilhoes de conexoes e o corpo triplicou de peso. Uma jornada extraordinaria."},en:{t:"Almost 1 year!",b:"Near her first birthday, Louise has come an incredible way: from helpless newborn to little explorer with personality, preferences, communication and attachment. In 52 weeks, her brain formed trillions of connections and her body tripled in weight. An extraordinary journey."}},
  // Week 52
  {pt:{t:"Feliz primeiro aniversario! 🎂",b:"1 ano! Louise triplicou o peso de nascimento, cresceu cerca de 25cm, formou trilhoes de sinapses cerebrais, aprendeu a reconhecer voces, se comunicar, explorar. E voces? Viveram a fase mais intensa da parentalidade. Se orgulhem: vocaloes sao o motivo dela estar aqui hoje, feliz e amada."},en:{t:"Happy first birthday! 🎂",b:"1 year! Louise tripled her birth weight, grew about 25cm, formed trillions of brain synapses, learned to recognize you, communicate, explore. And you? You lived through the most intense phase of parenthood. Be proud: you two are why she's here today, happy and loved."}},
];

// ──────────────────────────────────────────────────────
//   MONTHLY MILESTONES (months 2-12)
// ──────────────────────────────────────────────────────

window.MILESTONES=[
  {m:2,pt:{t:"2 meses completos! 🎉",b:"O ritmo circadiano esta amadurecendo — noites começam a ficar mais longas. Louise agora sorri intencionalmente, arrulha e reconhece sua voz. O cerebro formou trilhoes de novas conexoes neurais. O periodo mais caotico esta ficando para tras."},en:{t:"2 months complete! 🎉",b:"The circadian rhythm is maturing — nights are starting to get longer. Louise now smiles intentionally, coos, and recognizes your voice. The brain formed trillions of new neural connections. The most chaotic period is being left behind."}},
  {m:3,pt:{t:"3 meses! Sorriso e risadas 😊",b:"Louise sorri, arrulha e pode dar as primeiras risadas. Segue objetos com os olhos de forma fluida, distingue cores basicas, descobre as proprias maos. A personalidade dela esta comecando a aparecer — e voce ja reconhece o 'tom' unico do choro, do riso e dos olhares dela."},en:{t:"3 months! Smiles and giggles 😊",b:"Louise smiles, coos, and may give her first giggles. Smoothly follows objects with her eyes, distinguishes basic colors, discovers her own hands. Her personality is starting to emerge — and you already recognize the unique 'tone' of her crying, laughing, and gazing."}},
  {m:4,pt:{t:"4 meses! Gargalhadas e rolar 😂",b:"Prepare-se para gargalhadas fortes. Louise ja pode rolar de bruco para costas. Segura a cabeca firme quando sentada com apoio. O balbucio comeca com consoantes ('ba', 'da'). O sono pode temporariamente piorar ('regressao dos 4 meses') — mas e sinal de amadurecimento, nao regressao."},en:{t:"4 months! Laughs and rolls 😂",b:"Get ready for strong laughter. Louise can roll from tummy to back. Holds her head firm when sitting supported. Babbling begins with consonants ('ba', 'da'). Sleep may temporarily worsen ('4-month regression') — but it's a sign of maturation, not regression."}},
  {m:5,pt:{t:"5 meses! Curiosa e alcançando 🔍",b:"Louise alcança objetos com precisao, passa de uma mao para outra, leva tudo a boca. Sentando com menos apoio. Reconhece o proprio nome. As cores fazem muito mais sentido agora — brinquedos coloridos viram mundo novo."},en:{t:"5 months! Curious and reaching 🔍",b:"Louise reaches objects with precision, passes from one hand to the other, puts everything in her mouth. Sitting with less support. Recognizes her own name. Colors make much more sense now — colorful toys become a whole new world."}},
  {m:6,pt:{t:"6 meses! Alimentos solidos 🥕",b:"Metade do primeiro ano passou. Hora dos primeiros sabores: purês, alimentos amassados, baby-led weaning. O leite ainda e a base, mas o mundo de texturas e sabores esta abrindo. Louise pode sentar brevemente sem apoio, e pode começar a mostrar estranhamento com pessoas novas."},en:{t:"6 months! Solid foods 🥕",b:"Half of the first year is over. Time for first flavors: purees, mashed foods, baby-led weaning. Milk is still the base, but a world of textures and tastes is opening. Louise can briefly sit without support, and may start showing stranger wariness."}},
  {m:7,pt:{t:"7 meses! Sentando sozinha 💪",b:"Louise provavelmente ja senta sem apoio por periodos mais longos. Pode comecar a se arrastar, rolar continuamente ou engatinhar. Ansiedade de separacao pode surgir — ela sabe que voce existe mesmo quando sai da sala, e isso e novo. Peek-a-boo vira um dos jogos favoritos."},en:{t:"7 months! Sitting alone 💪",b:"Louise probably sits without support for longer periods. May start scooting, rolling continuously, or crawling. Separation anxiety may emerge — she knows you exist even when you leave the room, and that's new. Peek-a-boo becomes a favorite game."}},
  {m:8,pt:{t:"8 meses! Permanencia do objeto",b:"Louise entende que objetos escondidos continuam existindo. Procura coisas quando caem. Balbucia 'mamama' e 'dadada' (ainda sem associar a pessoas). Pode estranhar pessoas novas — sinal de que o vinculo com voces esta forte. Engatinhar, escorregar ou rolar se intensificam."},en:{t:"8 months! Object permanence",b:"Louise understands that hidden objects still exist. Looks for things when they fall. Babbles 'mamama' and 'dadada' (still without associating to people). May show stranger anxiety — sign that her bond with you is strong. Crawling, scooting or rolling intensifies."}},
  {m:9,pt:{t:"9 meses! Exploradora 🧭",b:"Engatinhando ou ja tentando ficar de pe com apoio. Pinca imatura desenvolvida — consegue pegar objetos pequenos. Comeca a entender 'nao'. Aponta para coisas. Imita gestos simples (bater palmas, dar tchau). E hora de reforcar a seguranca da casa definitivamente."},en:{t:"9 months! Explorer 🧭",b:"Crawling or already trying to pull up to stand. Immature pincer grasp developed — can pick up small objects. Starts understanding 'no'. Points at things. Imitates simple gestures (clapping, waving). Time to baby-proof the house definitively."}},
  {m:10,pt:{t:"10 meses! Cruising ✌️",b:"Louise anda de lado segurando em moveis (cruising). Pinca fina desenvolvendo — polegar e indicador nas pontas. Entende dezenas de palavras mesmo sem falar. Imita comportamentos complexos. Pode ter apego a um objeto de transicao (paninho, pelucia)."},en:{t:"10 months! Cruising ✌️",b:"Louise walks sideways holding furniture (cruising). Fine pincer developing — thumb and index at the tips. Understands dozens of words without speaking. Imitates complex behaviors. May have attachment to a transitional object (blankie, plushie)."}},
  {m:11,pt:{t:"11 meses! Quase andando 🚶",b:"Louise pode ficar de pe sozinha por segundos e dar os primeiros passos instaveis. Primeiras palavras podem aparecer — 'mama', 'papa', 'oi'. Compreende comandos simples. Aponta para pedir ou compartilhar atencao. A personalidade dela esta evidente em cada gesto."},en:{t:"11 months! Almost walking 🚶",b:"Louise may stand alone for seconds and take first unsteady steps. First words may appear — 'mama', 'dada', 'hi'. Understands simple commands. Points to ask or share attention. Her personality shows in every gesture."}},
  {m:12,pt:{t:"1 ANO! 🎂🎉",b:"Parabens!! De um recem-nascido indefeso a uma pessoinha cheia de personalidade em 12 meses. Louise triplicou o peso de nascimento, cresceu 25cm, formou trilhoes de sinapses. Aprendeu a reconhecer voces, se mover, se comunicar, amar. Que jornada incrivel. Voces, Louise e a familia inteira, sao demais!"},en:{t:"1 YEAR! 🎂🎉",b:"Congratulations!! From a helpless newborn to a little person full of personality in 12 months. Louise tripled her birth weight, grew 25cm, formed trillions of synapses. She learned to recognize you, move, communicate, love. What an incredible journey. You, Louise, and the whole family — you're amazing!"}},
];
