// ╔══════════════════════════════════════════════════════╗
// ║  LOUISE PRO · CURIOSITIES + MILESTONES               ║
// ║  Daily curiosities (days 1-30) + monthly milestones  ║
// ║  (months 2-12), bilingual EN/PT                      ║
// ║                                                      ║
// ║  Exposes: window.CURIOSITIES, window.MILESTONES      ║
// ╚══════════════════════════════════════════════════════╝

window.CURIOSITIES=[
  {pt:{t:"Bem-vinda ao mundo!",b:"Recém-nascidos só enxergam de 20-30cm. O mundo é preto, branco e tons de cinza. Seu rosto é a coisa favorita!"},en:{t:"Welcome to the world!",b:"Newborns can only see 20-30cm away. The world is black, white and shades of gray. Your face is her favorite thing!"}},
  {pt:{t:"O olfato é o superpoder",b:"Seu bebê reconhece o cheiro da mãe desde o primeiro dia. É o sentido mais desenvolvido ao nascer!"},en:{t:"Smell is the superpower",b:"Your baby recognizes mom's scent from day one. It's the most developed sense at birth!"}},
  {pt:{t:"Reflexos incríveis",b:"O reflexo de preensão é tão forte que o bebê consegue suportar seu próprio peso segurando seus dedos!"},en:{t:"Incredible reflexes",b:"The grip reflex is so strong that your baby could support their own weight holding your fingers!"}},
  {pt:{t:"Sono de recém-nascido",b:"Bebês dormem 16-17h por dia, mas em ciclos de 2-4h. Cada ciclo de sono dura só 50 minutos (adulto: 90min)."},en:{t:"Newborn sleep",b:"Babies sleep 16-17h/day but in 2-4h cycles. Each sleep cycle is only 50 minutes (adult: 90min)."}},
  {pt:{t:"O choro é comunicação",b:"Seu bebê já tem pelo menos 3 tipos de choro diferentes: fome, sono e desconforto. Com o tempo você vai distinguir cada um!"},en:{t:"Crying is communication",b:"Your baby already has at least 3 different cry types: hunger, sleep and discomfort. You'll learn to tell them apart!"}},
  {pt:{t:"Crescimento acelerado",b:"O cérebro do bebê cresce 1% ao dia nesta fase. Aos 3 meses terá dobrado de tamanho em relação ao nascimento!"},en:{t:"Rapid growth",b:"Your baby's brain grows 1% per day at this stage. By 3 months it will have doubled in size from birth!"}},
  {pt:{t:"O cordão vai cair logo",b:"Entre 7-21 dias o coto do cordão seca e cai naturalmente. Mantenha limpo e seco — não precisa puxar!"},en:{t:"The cord will fall soon",b:"Between 7-21 days the cord stump dries and falls naturally. Keep it clean and dry — no need to pull!"}},
  {pt:{t:"Pele a pele é remédio",b:"O contato pele a pele regula temperatura, batimentos cardíacos e reduz o estresse. 1 hora por dia faz diferença enorme!"},en:{t:"Skin to skin is medicine",b:"Skin-to-skin contact regulates temperature, heart rate and reduces stress. 1 hour daily makes a huge difference!"}},
  {pt:{t:"Ela ouve sua voz",b:"Bebês preferem vozes femininas e agudas. Aquela voz fina que você faz sem pensar? É instinto — e funciona!"},en:{t:"She hears your voice",b:"Babies prefer female, high-pitched voices. That silly voice you make without thinking? It's instinct — and it works!"}},
  {pt:{t:"O leite muda de cor",b:"O leite materno muda de composição ao longo do dia: mais gordura à noite para ajudar o sono, mais energia de manhã!"},en:{t:"Milk changes color",b:"Breast milk changes composition throughout the day: more fat at night to help sleep, more energy in the morning!"}},
  {pt:{t:"Bebês nascem nadadores",b:"O reflexo de mergulho faz o bebê prender a respiração automaticamente quando o rosto toca a água. Incrível, né?"},en:{t:"Babies are born swimmers",b:"The diving reflex makes babies automatically hold their breath when their face touches water. Amazing, right?"}},
  {pt:{t:"O sorriso está chegando",b:"Os primeiros sorrisos reflexos já podem aparecer, especialmente durante o sono. O sorriso social vem por volta de 6-8 semanas!"},en:{t:"The smile is coming",b:"First reflex smiles may already appear, especially during sleep. The social smile comes around 6-8 weeks!"}},
  {pt:{t:"Ela já sonha!",b:"Bebês passam 50% do sono em fase REM (adultos: 20%). Cientistas acreditam que eles já sonham — provavelmente com você!"},en:{t:"She already dreams!",b:"Babies spend 50% of sleep in REM phase (adults: 20%). Scientists believe they already dream — probably about you!"}},
  {pt:{t:"Recuperou o peso!",b:"A maioria dos bebês perde 5-10% do peso nos primeiros dias e recupera por volta do dia 10-14. Ela está crescendo!"},en:{t:"Weight recovered!",b:"Most babies lose 5-10% of birth weight in first days and regain it by day 10-14. She's growing perfectly!"}},
  {pt:{t:"Micro expressões",b:"Seu bebê já imita expressões faciais! Se você mostrar a língua bem devagar, ela pode tentar copiar. Teste!"},en:{t:"Micro expressions",b:"Your baby already mimics facial expressions! If you slowly stick out your tongue, she may try to copy. Try it!"}},
  {pt:{t:"Barulho branco é calmante",b:"Sons como secador, aspirador ou 'shhhh' lembram o útero (que era barulhento!). Pode usar para acalmar o choro."},en:{t:"White noise is soothing",b:"Sounds like hair dryers, vacuums or 'shhhh' remind them of the womb (which was noisy!). Great for calming crying."}},
  {pt:{t:"A fontanela pulsa",b:"A moleira do bebê pulsa com os batimentos cardíacos. É normal! Ela protege o cérebro e permite que a cabeça cresça."},en:{t:"The fontanelle pulses",b:"The baby's soft spot pulses with the heartbeat. It's normal! It protects the brain and allows the head to grow."}},
  {pt:{t:"Sem lágrimas ainda",b:"Recém-nascidos choram sem lágrimas! As glândulas lacrimais só amadurecem por volta de 3-4 semanas."},en:{t:"No tears yet",b:"Newborns cry without tears! The tear glands only mature around 3-4 weeks."}},
  {pt:{t:"O toque é aprendizado",b:"Cada vez que você toca seu bebê, milhares de conexões neurais se formam. Massagem infantil é estimulação pura!"},en:{t:"Touch is learning",b:"Every time you touch your baby, thousands of neural connections form. Baby massage is pure stimulation!"}},
  {pt:{t:"Ela reconhece idiomas",b:"Bebês conseguem distinguir todos os fonemas de todos os idiomas. Essa habilidade diminui aos 10 meses, focando na língua materna."},en:{t:"She recognizes languages",b:"Babies can distinguish all phonemes from all languages. This ability decreases by 10 months, focusing on the native language."}},
  {pt:{t:"Padrão de sono formando",b:"As janelas de sono vão ficando mais definidas. O ritmo circadiano começa a se formar, orientado pela luz do dia."},en:{t:"Sleep pattern forming",b:"Wake windows are becoming more defined. The circadian rhythm is starting to form, guided by daylight."}},
  {pt:{t:"O estômago é minúsculo",b:"O estômago do recém-nascido tem o tamanho de uma cereja no dia 1, uma noz no dia 3, e um ovo aos 10 dias!"},en:{t:"The stomach is tiny",b:"A newborn's stomach is the size of a cherry on day 1, a walnut by day 3, and an egg by day 10!"}},
  {pt:{t:"Bebês preferem padrões",b:"Seu bebê prefere olhar para padrões de alto contraste — listras preto e branco são mais interessantes que cores!"},en:{t:"Babies prefer patterns",b:"Your baby prefers looking at high-contrast patterns — black and white stripes are more interesting than colors!"}},
  {pt:{t:"A voz do pai acalma",b:"Estudos mostram que a voz grave do pai pode ser tão calmante quanto a da mãe. Converse, cante — ela está ouvindo!"},en:{t:"Dad's voice calms",b:"Studies show that dad's deep voice can be as soothing as mom's. Talk, sing — she's listening!"}},
  {pt:{t:"Movimentos reflexos",b:"Os movimentos 'de susto' (reflexo de Moro) são normais e vão diminuir até os 4 meses. O swaddle ajuda!"},en:{t:"Reflex movements",b:"The 'startle' movements (Moro reflex) are normal and will decrease by 4 months. Swaddling helps!"}},
  {pt:{t:"Ela reconhece seu rosto!",b:"Com 4 semanas, bebês focam em objetos de 20-30cm — a distância do seu rosto durante a amamentação. Ela estuda cada detalhe!"},en:{t:"She recognizes your face!",b:"At 4 weeks, babies focus on objects 20-30cm away — the distance to your face during breastfeeding. She's studying every detail!"}},
  {pt:{t:"O intestino está aprendendo",b:"Cólicas são comuns entre 2-12 semanas. O sistema digestivo ainda está amadurecendo — vai melhorar!"},en:{t:"The gut is learning",b:"Colic is common between 2-12 weeks. The digestive system is still maturing — it will get better!"}},
  {pt:{t:"Quase 1 mês!",b:"Em 28 dias, o cérebro cresceu 15%. Ela já segue objetos com os olhos e reconhece sua voz entre outras. Incrível evolução!"},en:{t:"Almost 1 month!",b:"In 28 days, the brain has grown 15%. She already follows objects with her eyes and recognizes your voice among others!"}},
  {pt:{t:"Músculos do pescoço",b:"O bebê já começa a tentar erguer a cabeça brevemente durante o tummy time. Cada segundo fortalece os músculos!"},en:{t:"Neck muscles",b:"Your baby is starting to briefly lift her head during tummy time. Every second strengthens the muscles!"}},
  {pt:{t:"1 mês completo! 🎉",b:"Parabéns! Seu bebê já cresceu cerca de 3-4cm e ganhou ~700g. O período mais intenso está passando. Vocês estão indo muito bem!"},en:{t:"1 month complete! 🎉",b:"Congratulations! Your baby has grown about 3-4cm and gained ~700g. The most intense period is passing. You're doing great!"}},
];
window.MILESTONES=[
  {m:2,pt:{t:"2 meses completos! 🎉",b:"O ritmo circadiano está amadurecendo! O sono começa a ficar mais previsível. O Sleep Engine agora aprende a rotina pessoal da Louise."},en:{t:"2 months complete! 🎉",b:"The circadian rhythm is maturing! Sleep is becoming more predictable. The Sleep Engine is now learning Louise's personal routine."}},
  {m:3,pt:{t:"3 meses! O sorriso social chegou! 😊",b:"Louise já sorri intencionalmente e pode começar a balbuciar. Ela segue objetos com os olhos e está descobrindo as próprias mãos!"},en:{t:"3 months! The social smile is here! 😊",b:"Louise now smiles intentionally and may start cooing. She follows objects with her eyes and is discovering her own hands!"}},
  {m:4,pt:{t:"4 meses! Risadas! 😂",b:"Prepare-se para as primeiras gargalhadas! Ela já rola de bruços para costas e pode começar a pegar objetos com as mãos."},en:{t:"4 months! Laughs! 😂",b:"Get ready for the first giggles! She already rolls from tummy to back and may start grasping objects."}},
  {m:5,pt:{t:"5 meses! Curiosa 🔍",b:"Tudo vai pra boca! Ela está explorando texturas e pode começar a sentar com apoio."},en:{t:"5 months! Curious 🔍",b:"Everything goes to the mouth! She's exploring textures and may start sitting with support."}},
  {m:6,pt:{t:"6 meses! Introdução alimentar 🥕",b:"Hora da papinha! O sistema digestivo está pronto para alimentos sólidos. Um novo mundo de sabores começa!"},en:{t:"6 months! Solid food time 🥕",b:"Time for solids! The digestive system is ready for solid food. A whole new world of flavors begins!"}},
  {m:7,pt:{t:"7 meses! Sentando sozinha 💪",b:"Louise provavelmente já senta sem apoio! Pode começar a engatinhar ou se arrastar. O mundo ficou maior!"},en:{t:"7 months! Sitting alone 💪",b:"Louise probably sits without support now! She may start crawling or scooting. The world just got bigger!"}},
  {m:8,pt:{t:"8 meses! Ansiedade de separação",b:"É normal ela estranhar outras pessoas. Significa que o vínculo com vocês está forte. Paciência — passa!"},en:{t:"8 months! Separation anxiety",b:"It's normal for her to be wary of others. It means the bond with you is strong. Patience — it passes!"}},
  {m:9,pt:{t:"9 meses! Exploradora 🧭",b:"Engatinhando ou se puxando pra ficar de pé. O 'não' começa a ter significado. Hora de revisar a segurança da casa!"},en:{t:"9 months! Explorer 🧭",b:"Crawling or pulling to stand. 'No' starts to have meaning. Time to baby-proof the house!"}},
  {m:10,pt:{t:"10 meses! Pinça fina ✌️",b:"Ela já pega objetos pequenos com polegar e indicador. Adora bater palmas e dar tchau!"},en:{t:"10 months! Pincer grasp ✌️",b:"She now picks up small objects with thumb and index finger. Loves clapping and waving!"}},
  {m:11,pt:{t:"11 meses! Quase andando 🚶‍♀️",b:"Ficando de pé sozinha e dando os primeiros passos segurando em móveis. As primeiras palavras podem aparecer!"},en:{t:"11 months! Almost walking 🚶‍♀️",b:"Standing alone and taking first steps holding furniture. First words may appear!"}},
  {m:12,pt:{t:"1 ANO! 🎂🎉",b:"Parabéns!! De um recém-nascido a uma pessoinha cheia de personalidade. Que jornada incrível! Louise e vocês são demais!"},en:{t:"1 YEAR! 🎂🎉",b:"Congratulations!! From a newborn to a little person full of personality. What an incredible journey! Louise and you are amazing!"}},
];
