// ── RELATÓRIO DE 30 DIAS · página-documento (v11.9.136) ──
// Aprovado do mockup `.claude/mockups/relatorio-30d.html`. Três blocos: médias, MAPA dos 30
// dias (actograma — cada linha é um dia das 00h às 24h) e tabela dia a dia.
// ⚠️ Paleta CLARA de propósito: isto é um DOCUMENTO pra imprimir/enviar à pediatra, não uma
// tela do app — por isso não usa os tokens escuros do `T` nem a escala tipográfica da UI
// (usa a escala do documento). É a única tela do app assim, e é intencional.
//
// v11.9.137: ⚠️ window.print() é NO-OP em PWA standalone no iOS (mesma família da landmine
// dos haptics) — o William confirmou no device. O botão "Salvar" agora RENDERIZA O DOCUMENTO
// NUM CANVAS (função abaixo, zero dependência) e entrega o PNG pro share sheet nativo, que
// funciona no standalone: WhatsApp, Salvar em Arquivos e Imprimir saem todos dali.
// window.print() ficou só como fallback de desktop (onde funciona e gera PDF real).

// Desenha o relatório inteiro num canvas 2x (data-driven a partir do `rep` — não lê o DOM).
// Layout espelha a página: cabeçalho, 4 KPIs, mapa (actograma), tabela 11 colunas, rodapé.
function renderReportCanvas(rep,opts){
  const en=opts.lang==="en";
  const loc=en?"en-US":"pt-BR";
  const dShort=d=>new Date(d+"T12:00:00").toLocaleDateString(loc,{day:"2-digit",month:"2-digit"});
  const dLong=d=>new Date(d+"T12:00:00").toLocaleDateString(loc,{day:"numeric",month:"long"});
  const rows=rep.rows.slice().reverse();
  const withN=rep.rows.filter(r=>r.night),withNap=rep.rows.filter(r=>r.napCount>0),
        withF=rep.rows.filter(r=>r.feedCount>0),withW=rep.rows.filter(r=>r.maxWindowMin>0);
  const avg=(a,f)=>a.length?Math.round(a.reduce((s,x)=>s+f(x),0)/a.length):0;
  const avg1=(a,f)=>a.length?(a.reduce((s,x)=>s+f(x),0)/a.length).toFixed(1).replace(".",en?".":","):"0";
  // v11.9.141: mesmo critério de outlier da tela (não redraw de gráfico novo — só dobra a
  // linha de subtítulo do KPI de sono noturno quando existe alguma noite atípica de verdade).
  const withNClean=withN.filter(r=>!r.nightOutlier);
  const outlierCount=withN.length-withNClean.length;
  // v11.9.144: no canvas as tags viram sigla de 3 letras em vez de emoji — emoji em canvas 2D
  // depende de fonte do sistema e imprime mal em P&B; a pediatra recebe isto impresso.
  const TAG_ABBR={vaccine:en?"VAC":"VAC",teething:en?"TTH":"DEN",illness:en?"ILL":"DOE",newfood:en?"FOD":"ALI",cosleep:en?"CSL":"C-S"};
  // W=920: soma das 17 colunas + gaps + 2×PAD dá 902px de mínimo (medido com measureText
  // sobre os 30 dias reais); os ~18px de folga evitam que um valor mais longo que os atuais
  // (ex: 3 tags no mesmo dia) encoste na margem direita.
  const S=2,W=920,PAD=28;
  const mapRowH=13,tblRowH=13.5;
  const mapY=224,mapH=rows.length*mapRowH;
  const tblTitleY=mapY+mapH+30,theadY=tblTitleY+32,tbodyY=theadY+14;
  const footY=tbodyY+rows.length*tblRowH+16;
  // v11.9.144: +13px de folga pra linha de legenda de contexto quando ela existir.
  const _hasTagRow=rep.rows.some(r=>r.tags&&r.tags.length);
  const H=footY+(_hasTagRow?57:44);
  const canvas=document.createElement("canvas");
  canvas.width=W*S;canvas.height=Math.ceil(H)*S;
  const ctx=canvas.getContext("2d");
  ctx.scale(S,S);
  const F=w=>`${w} -apple-system,'Segoe UI',system-ui,sans-serif`;
  const box=(x,y,w,h,r,fill,stroke)=>{ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x,y,w,h,r);else ctx.rect(x,y,w,h);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke()}};
  // fundo
  ctx.fillStyle="#ffffff";ctx.fillRect(0,0,W,H);
  // ── cabeçalho ──
  ctx.fillStyle="#23263f";ctx.font=F("700 20px");ctx.textBaseline="alphabetic";
  ctx.fillText((opts.babyName||"Louise")+(en?" · Sleep & routine":" · Sono e rotina"),PAD,44);
  ctx.fillStyle="#6b7090";ctx.font=F("400 11.5px");
  ctx.fillText(dLong(rep.from)+(en?" to ":" a ")+dLong(rep.to)+" · 30 "+(en?"days":"dias"),PAD,62);
  ctx.fillStyle="#8b90ad";ctx.font=F("400 10px");ctx.textAlign="right";
  let my=36;
  if(opts.ageStr){ctx.fillText((en?"Age: ":"Idade: ")+opts.ageStr,W-PAD,my);my+=14}
  if(opts.birthDate){ctx.fillText((en?"Born ":"Nascimento: ")+dLong(opts.birthDate)+(en?"":" de ")+new Date(opts.birthDate+"T12:00:00").getFullYear(),W-PAD,my);my+=14}
  ctx.fillText(en?"Generated by Louise Pro":"Gerado pelo Louise Pro",W-PAD,my);
  ctx.textAlign="left";
  ctx.fillStyle="#5b4fc4";ctx.fillRect(PAD,72,W-2*PAD,2.5);
  // ── KPIs ──
  const kw=(W-2*PAD-3*10)/4,ky=90;
  const kpis=[
    [en?"NIGHT SLEEP":"SONO NOTURNO",fmtDur(avg(withN,r=>r.night.durationMin)),(en?"real ":"real ")+fmtDur(avg(withN,r=>r.night.realMin))+" · "+avg1(withN,r=>r.night.wakings)+(en?" wakings":" despertares")+(outlierCount>0?(en?` · excl. ${outlierCount}: ${fmtDur(avg(withNClean,r=>r.night.durationMin))}`:` · sem ${outlierCount} atíp.: ${fmtDur(avg(withNClean,r=>r.night.durationMin))}`):"")],
    [en?"NAPS":"SONECAS",avg1(withNap,r=>r.napCount)+(en?"/day":"/dia"),fmtDur(avg(withNap,r=>r.napTotalMin))+(en?" total":" no total")],
    [en?"AWAKE WINDOW":"JANELA ACORDADA",fmtDur(avg(withW,r=>r.maxWindowMin)),en?"longest of the day (avg)":"maior do dia (média)"],
    [en?"FEEDS":"MAMADAS",avg1(withF,r=>r.feedCount)+(en?"/day":"/dia"),avg(withF,r=>r.mlTotal)+(en?"ml per day":"ml por dia")]
  ];
  kpis.forEach((k,i)=>{
    const x=PAD+i*(kw+10);
    box(x,ky,kw,64,8,"#fafaff","#e2e3ef");
    ctx.fillStyle="#7b80a0";ctx.font=F("700 8.5px");ctx.fillText(k[0],x+11,ky+18);
    ctx.fillStyle="#2d2f57";ctx.font=F("700 17px");ctx.fillText(k[1],x+11,ky+40);
    ctx.fillStyle="#7b80a0";ctx.font=F("400 9.5px");ctx.fillText(k[2],x+11,ky+55);
  });
  // ── mapa ──
  ctx.fillStyle="#23263f";ctx.font=F("700 12.5px");
  ctx.fillText(en?"30-day map":"Mapa dos 30 dias",PAD,182);
  // legenda
  let lx=PAD;const ly=192;
  const leg=[[en?"Night sleep":"Sono noturno","#4c4f8f",15],[en?"Nap":"Soneca","#9b8df8",15],[en?"Awake":"Acordada","#f4f5fa",15],[en?"Feed":"Mamada","#e08a1e",2.5]];
  ctx.font=F("400 9.5px");
  leg.forEach(l=>{
    ctx.fillStyle=l[1];ctx.fillRect(lx,ly,l[2],8);
    if(l[1]==="#f4f5fa"){ctx.strokeStyle="#e2e3ef";ctx.lineWidth=1;ctx.strokeRect(lx+0.5,ly+0.5,l[2]-1,7)}
    lx+=l[2]+5;ctx.fillStyle="#5a5f80";ctx.fillText(l[0],lx,ly+8);lx+=ctx.measureText(l[0]).width+13;
  });
  const tx0=PAD+56,tw=W-PAD-tx0;
  // eixo de horas
  ctx.fillStyle="#9a9fbb";ctx.font=F("400 8.5px");
  [0,6,12,18,24].forEach(h=>{
    const x=tx0+h/24*tw;
    ctx.textAlign=h===0?"left":h===24?"right":"center";
    ctx.fillText(String(h).padStart(2,"0")+"h",x,mapY-6);
  });
  ctx.textAlign="left";
  rows.forEach((r,i)=>{
    const y=mapY+i*mapRowH;
    ctx.fillStyle="#7b80a0";ctx.font=F("400 8.5px");
    ctx.fillText(_rpWd(r.date,en)+" "+dShort(r.date),PAD,y+8.5);
    ctx.fillStyle="#f4f5fa";ctx.fillRect(tx0,y,tw,10);
    ctx.fillStyle="#e6e7f1";for(let h=3;h<24;h+=3)ctx.fillRect(tx0+h/24*tw,y,1,10);
    ctx.fillStyle="#4c4f8f";r.sleepSegs.forEach(s=>ctx.fillRect(tx0+s.from/1440*tw,y,Math.max(1,(s.to-s.from)/1440*tw),10));
    ctx.fillStyle="#9b8df8";r.napSegs.forEach(s=>ctx.fillRect(tx0+s.from/1440*tw,y,Math.max(1,(s.to-s.from)/1440*tw),10));
    ctx.fillStyle="#e08a1e";r.feedMins.forEach(m=>ctx.fillRect(tx0+m/1440*tw,y-3,1.5,4));
  });
  // ── tabela ──
  ctx.fillStyle="#23263f";ctx.font=F("700 12.5px");
  ctx.fillText(en?"Day by day":"Dia a dia",PAD,tblTitleY);
  ctx.fillStyle="#7b80a0";ctx.font=F("400 9px");
  ctx.fillText(en?"Real sleep = night minus wakings. Pre-sleep window = the one right before bedtime. Amber row = atypical night (<6h or started ≥23h).":"Sono real = noite menos os despertares. Janela pré-sono = a que vem antes do bedtime. Linha âmbar = noite atípica (<6h ou começou às 23h+).",PAD,tblTitleY+14);
  // v11.9.141: colunas por ORÇAMENTO DE LARGURA (não mais x hardcoded coluna a coluna) —
  // mais fácil de ajustar/adicionar coluna sem recalcular tudo a mão. x é derivado: coluna
  // left-aligned desenha na borda esquerda do slot, right-aligned na borda direita.
  const GAP=7;
  const colDefs=[
    {w:62,a:"left",h:en?"DAY":"DIA",f:r=>_rpWd(r.date,en)+" "+dShort(r.date)},
    {w:36,a:"left",h:en?"WOKE":"ACORDOU",f:r=>r.wake||"—"},
    {w:72,a:"left",h:en?"NIGHT":"NOITE",f:r=>r.night?r.night.start+"→"+r.night.end:"—"},
    {w:44,a:"right",h:en?"DUR.":"DURAÇÃO",f:r=>r.night?fmtDur(r.night.durationMin):"—"},
    {w:24,a:"right",h:"DESP.",he:"WAK.",f:r=>r.night?String(r.night.wakings):"—"},
    {w:50,a:"right",h:en?"WAK.(m)":"DESP.(m)",f:r=>r.wakingDurations.length?r.wakingDurations.join(","):"—"},
    {w:38,a:"right",h:en?"REAL":"SONO REAL",f:r=>r.night?fmtDur(r.night.realMin):"—"},
    {w:44,a:"right",h:en?"DAY TOT.":"S.TOTAL",f:r=>r.totalSleepMin?fmtDur(r.totalSleepMin):"—"},
    {w:24,a:"right",h:en?"NAPS":"SONEC.",f:r=>r.napCount?String(r.napCount):"—"},
    {w:36,a:"right",h:"TOTAL",f:r=>r.napTotalMin?fmtDur(r.napTotalMin):"—"},
    {w:52,a:"right",h:en?"1ST NAP":"1a SONECA",f:r=>r.firstNapMin?`${fmtDur(r.firstNapMin)} ${r.firstNapStart}`:"—"},
    {w:54,a:"right",h:en?"NAPS(m)":"SONEC.(m)",f:r=>r.napDurations.length?r.napDurations.join(","):"—"},
    {w:36,a:"right",h:en?"WINDOW":"JANELA",f:r=>r.maxWindowMin?fmtDur(r.maxWindowMin):"—"},
    {w:40,a:"right",h:en?"PRE-SLP":"PRÉ-SONO",f:r=>r.preBedWindowMin?fmtDur(r.preBedWindowMin):"—"},
    {w:24,a:"right",h:en?"FEEDS":"MAMAD.",f:r=>r.feedCount?String(r.feedCount):"—"},
    {w:38,a:"right",h:en?"MILK":"LEITE",f:r=>r.mlTotal?r.mlTotal+"ml":"—"},
    {w:60,a:"left",h:en?"CONTEXT":"CONTEXTO",f:r=>(r.tags&&r.tags.length)?r.tags.map(k=>TAG_ABBR[k]||k).join(" "):""}
  ];
  let cx=PAD;
  const cols=colDefs.map(c=>{const x=c.a==="left"?cx:cx+c.w;cx+=c.w+GAP;return{...c,x}});
  ctx.font=F("700 7.3px");ctx.fillStyle="#7b80a0";
  cols.forEach(c=>{ctx.textAlign=c.a;ctx.fillText(en&&c.he?c.he:c.h,c.x,theadY)});
  ctx.fillStyle="#d8dae8";ctx.fillRect(PAD,theadY+4,W-2*PAD,1.5);
  rows.forEach((r,i)=>{
    const y=tbodyY+i*tblRowH;
    // v11.9.144: dia de hoje (incompleto) em cinza — não entra em nenhuma média
    if(r.partial){ctx.fillStyle="#efeef8";ctx.fillRect(PAD,y,W-2*PAD,tblRowH)}
    else if(r.nightOutlier){ctx.fillStyle="#fbf1de";ctx.fillRect(PAD,y,W-2*PAD,tblRowH)}
    else if(i%2){ctx.fillStyle="#fafaff";ctx.fillRect(PAD,y,W-2*PAD,tblRowH)}
    ctx.font=F("400 8.5px");
    cols.forEach((c,ci)=>{
      ctx.textAlign=c.a;
      ctx.fillStyle=ci===0?"#23263f":"#3a3d60";
      if(ci===0)ctx.font=F("600 8.5px");
      ctx.fillText(c.f(r),c.x,y+10);
      if(ci===0)ctx.font=F("400 8.5px");
    });
  });
  ctx.textAlign="left";
  // ── rodapé ──
  ctx.fillStyle="#e8e9f2";ctx.fillRect(PAD,footY,W-2*PAD,1);
  ctx.fillStyle="#8b90ad";ctx.font=F("400 9px");
  // v11.9.144: legenda das siglas de contexto — só aparece se houver tag no período
  const usedTags=Object.keys(EVENT_TAGS).filter(k=>rows.some(r=>r.tags&&r.tags.indexOf(k)>=0));
  const legend=usedTags.length
    ?(en?"Context: ":"Contexto: ")+usedTags.map(k=>`${TAG_ABBR[k]}=${en?EVENT_TAGS[k].en:EVENT_TAGS[k].pt}`).join(" · ")
    :"";
  const foot=en
    ?["Entries logged manually by the parents in the Louise Pro app — unlogged periods show as awake on the map.","Tracking document; does not replace professional evaluation."]
    :["Registros feitos manualmente pelos pais no app Louise Pro — períodos não registrados aparecem como acordada no mapa.","Documento de acompanhamento, não substitui avaliação profissional."];
  if(legend){ctx.fillStyle="#5a5f80";ctx.fillText(legend,PAD,footY+15);ctx.fillStyle="#8b90ad"}
  ctx.fillText(foot[0],PAD,footY+(legend?28:15));
  ctx.fillText(foot[1],PAD,footY+(legend?41:28));
  return canvas;
}

// v11.9.138: PDF DE VERDADE, escrito à mão (zero dependência). O truque: PDF aceita JPEG
// embutido cru (filtro DCTDecode) — então o canvas do documento vira JPEG e este builder
// monta o arquivo binário em volta (catalog/pages/page/imagem/conteúdo + xref com offsets
// em bytes). Página única com o tamanho exato do documento (~190 DPI). O que quebra PDFs
// feitos à mão são os offsets do xref — o harness confere cada um contra a posição real.
function _reportPdfBytes(jpeg,imgW,imgH){
  const pageW=595.28,pageH=Math.round(pageW*imgH/imgW*100)/100;
  const te=new TextEncoder();
  const chunks=[];let offset=0;const xref=[];
  const put=u8=>{chunks.push(u8);offset+=u8.length};
  const puts=s=>put(te.encode(s));
  puts("%PDF-1.4\n");
  put(new Uint8Array([0x25,0xE2,0xE3,0xCF,0xD3,0x0A]));
  const mark=n=>{xref[n]=offset};
  mark(1);puts("1 0 obj\n<</Type/Catalog/Pages 2 0 R>>\nendobj\n");
  mark(2);puts("2 0 obj\n<</Type/Pages/Kids[3 0 R]/Count 1>>\nendobj\n");
  mark(3);puts("3 0 obj\n<</Type/Page/Parent 2 0 R/MediaBox[0 0 "+pageW+" "+pageH+"]/Resources<</XObject<</Im1 4 0 R>>/ProcSet[/PDF/ImageC]>>/Contents 5 0 R>>\nendobj\n");
  mark(4);puts("4 0 obj\n<</Type/XObject/Subtype/Image/Width "+imgW+"/Height "+imgH+"/ColorSpace/DeviceRGB/BitsPerComponent 8/Filter/DCTDecode/Length "+jpeg.length+">>\nstream\n");
  put(jpeg);puts("\nendstream\nendobj\n");
  const content="q\n"+pageW+" 0 0 "+pageH+" 0 0 cm\n/Im1 Do\nQ";
  mark(5);puts("5 0 obj\n<</Length "+content.length+">>\nstream\n"+content+"\nendstream\nendobj\n");
  const xrefStart=offset;
  let x="xref\n0 6\n0000000000 65535 f \n";
  for(let i=1;i<=5;i++)x+=String(xref[i]).padStart(10,"0")+" 00000 n \n";
  x+="trailer\n<</Size 6/Root 1 0 R>>\nstartxref\n"+xrefStart+"\n%%EOF";
  puts(x);
  const total=new Uint8Array(offset);let p=0;for(const c of chunks){total.set(c,p);p+=c.length}
  return total;
}
async function renderReportPDF(rep,opts){
  const canvas=renderReportCanvas(rep,opts);
  const jblob=await new Promise((res,rej)=>canvas.toBlob(b=>b?res(b):rej(new Error("toBlob falhou")),"image/jpeg",0.92));
  const jpeg=new Uint8Array(await jblob.arrayBuffer());
  return new Blob([_reportPdfBytes(jpeg,canvas.width,canvas.height)],{type:"application/pdf"});
}

const ReportPage = React.memo(function ReportPage({entries,birthDate,babyName,onBack,lang}){
  const en=lang==="en";
  const rep=useMemo(()=>sleepReport(entries,30),[entries]);
  const corr=useMemo(()=>sleepCorrelations(rep),[rep]);
  // v11.9.144: mesma comparação, só nos dias sem tag de contexto — mostrada lado a lado.
  const corrClean=useMemo(()=>sleepCorrelations(rep,{cleanOnly:true}),[rep]);
  const rows=rep.rows.slice().reverse();
  // v11.9.144: hoje é um dia INCOMPLETO e não entra em NENHUMA média (ele ainda está
  // acontecendo — às 14h a Louise fez 2 das 4 sonecas). Antes ele contaminava todos os KPIs.
  const done=rep.rows.filter(r=>!r.partial);
  const withN=done.filter(r=>r.night),withNap=done.filter(r=>r.napCount>0),
        withF=done.filter(r=>r.feedCount>0),withW=done.filter(r=>r.maxWindowMin>0),
        withFN=done.filter(r=>r.firstNapMin>0);
  // v11.9.144: dias marcados com alguma tag de contexto (vacina/dente/doença/etc)
  const tagged=done.filter(r=>r.tags&&r.tags.length);
  const cleanN=withN.filter(r=>!(r.tags&&r.tags.length));
  const avg=(a,f)=>a.length?Math.round(a.reduce((s,x)=>s+f(x),0)/a.length):0;
  const avg1=(a,f)=>a.length?(a.reduce((s,x)=>s+f(x),0)/a.length).toFixed(1).replace(".",en?".":","):"0";
  const loc=en?"en-US":"pt-BR";
  const dShort=d=>new Date(d+"T12:00:00").toLocaleDateString(loc,{day:"2-digit",month:"2-digit"});
  const dLong=d=>new Date(d+"T12:00:00").toLocaleDateString(loc,{day:"numeric",month:"long"});
  const pc=m=>(m/1440*100).toFixed(2)+"%";
  let ageStr="";
  if(birthDate){const dd=Math.round((new Date(rep.to+"T12:00:00")-new Date(birthDate+"T12:00:00"))/864e5);
    const m=Math.floor(dd/30.4375),r=Math.round(dd-m*30.4375);
    ageStr=en?`${m} months and ${r} days`:`${m} meses e ${r} dias`}
  const onPrint=()=>{
    try{
      document.body.classList.add("print-report");
      const done=()=>{document.body.classList.remove("print-report");window.removeEventListener("afterprint",done)};
      window.addEventListener("afterprint",done);
      setTimeout(()=>{window.print();setTimeout(done,2000)},80);
    }catch(e){}
  };
  // v11.9.138: PDF DE VERDADE — canvas do documento → JPEG → arquivo .pdf montado à mão
  // (renderReportPDF acima). Share sheet com o .pdf no iOS (funciona no standalone);
  // fallback: download direto do arquivo (desktop). Nada depende de window.print.
  const[saving,setSaving]=useState(false);
  const onSave=async()=>{
    if(saving)return;setSaving(true);
    try{
      const blob=await renderReportPDF(rep,{lang,babyName,birthDate,ageStr});
      const fname=`${(babyName||"louise").toLowerCase().replace(/[^a-z0-9]/g,"")||"louise"}-30d-${todayStr()}.pdf`;
      const file=new File([blob],fname,{type:"application/pdf"});
      if(navigator.canShare&&navigator.canShare({files:[file]})){
        await navigator.share({files:[file],title:fname});
        Haptic.success();setSaving(false);return;
      }
      const url=URL.createObjectURL(blob);
      const a=document.createElement("a");a.href=url;a.download=fname;document.body.appendChild(a);a.click();
      setTimeout(()=>{document.body.removeChild(a);URL.revokeObjectURL(url)},1000);
      Haptic.success();
    }catch(e){/* AbortError = usuário fechou o share sheet */}
    setSaving(false);
  };
  const onShare=async()=>{
    try{
      const txt=sleepReportText(rep,lang,babyName);
      if(navigator.share)await navigator.share({title:en?"Sleep & routine report":"Relatório de sono e rotina",text:txt});
      else await navigator.clipboard.writeText(txt);
      Haptic.success();
    }catch(e){}
  };
  const K=({k,v,s,extra})=><div style={{border:"1px solid #e2e3ef",borderRadius:8,padding:"10px 11px",background:"#fafaff"}}>
    <div style={{fontSize:9,fontWeight:700,letterSpacing:.6,textTransform:"uppercase",color:"#7b80a0"}}>{k}</div>
    <div style={{fontSize:18,fontWeight:700,letterSpacing:-.5,marginTop:3,color:"#2d2f57"}}>{v}</div>
    <div style={{fontSize:10,color:"#7b80a0",marginTop:1}}>{s}</div>
    {extra}
  </div>;
  // v11.9.142: card de comparação de 2 grupos. "ok:false" = amostra pequena demais (<n
  // mínimo) — mostra isso explicitamente em vez de forçar uma média enganosa. `data.primary`
  // escolhe qual métrica vira o número grande (a que a comparação realmente pediu); "solid"
  // (revisão Opus+Fable) é um selo neutro/destacado — nunca um p-valor/correlação numérica,
  // que seria falsa precisão pra quem não é estatístico. `dayGap` expõe (não corrige) quando
  // os 2 grupos estão concentrados em semanas diferentes do mês — sinal de confundimento por
  // tendência (a Louise muda ao longo do próprio mês medido), não defeito da comparação.
  const Corr=({title,data,showNapAvg,clean})=>{
    const[gA,gB]=data.groups;
    const val=g=>data.primary==="wake"?_rpHHMM(g.wakeMin):data.primary==="wakings"?`${g.wakings} ${en?"wakings":"despertares"}`:fmtDur(g.nightMin);
    const sub=g=>data.primary==="wakings"?fmtDur(g.nightMin):`${g.wakings} ${en?"wakings":"despertares"}`;
    const bothOk=gA.ok&&gB.ok;
    return(<div style={{marginBottom:10}}>
    <div style={{display:"flex",alignItems:"center",gap:6,marginBottom:4,flexWrap:"wrap"}}>
      <div style={{fontSize:10.5,fontWeight:700,color:"#4a4f70"}}>{title}</div>
      {bothOk&&<span style={{fontSize:8,fontWeight:800,padding:"2px 6px",borderRadius:5,textTransform:"uppercase",letterSpacing:.4,background:data.solid?"#fdecc8":"#eef0f7",color:data.solid?"#a3792e":"#8b90ad"}}>
        {data.solid?(en?"worth watching":"vale observar"):(en?"normal range":"dentro do normal")}
      </span>}
    </div>
    <div style={{display:"flex",gap:8}}>
      {[gA,gB].map((g,i)=><div key={i} style={{flex:1,border:"1px solid #e2e3ef",borderRadius:8,padding:"8px 10px",background:"#fafaff"}}>
        <div style={{fontSize:9.5,fontWeight:700,color:"#7b80a0",textTransform:"uppercase",letterSpacing:.3}}>{g.label}{g.ok?` · n=${g.n}`:""}</div>
        {g.ok?<>
          <div style={{fontSize:14,fontWeight:700,color:"#2d2f57",marginTop:2}}>{val(g)}</div>
          <div style={{fontSize:9.5,color:"#7b80a0"}}>{sub(g)}</div>
          {showNapAvg&&g.avgNapMin!=null&&<div style={{fontSize:9.5,color:"#7b80a0"}}>{fmtDur(g.avgNapMin)} {en?"avg/nap":"média/soneca"}</div>}
        </>:<div style={{fontSize:9.5,color:"#b0b4c8",fontStyle:"italic",marginTop:2}}>{en?`not enough data (${g.n}/${corr.minN} days)`:`dado insuficiente (${g.n}/${corr.minN} dias)`}</div>}
      </div>)}
    </div>
    {bothOk&&data.dayGap>=5&&<div style={{fontSize:8.5,color:"#b0851f",marginTop:3,fontStyle:"italic"}}>{en?`Note: groups are ~${data.dayGap} days apart within the month — could reflect the month's own trend, not just this variable.`:`Nota: os grupos estão a ~${data.dayGap} dias de distância dentro do mês — pode refletir a tendência do próprio mês, não só essa variável.`}</div>}
    {/* v11.9.144: a MESMA comparação, só nos dias sem nada anormal marcado. Só aparece se
        os 2 grupos limpos tiverem N suficiente — senão seria número frágil disfarçado. */}
    {clean&&clean.groups[0].ok&&clean.groups[1].ok&&<div style={{fontSize:9,color:"#4a4f70",marginTop:4,padding:"6px 9px",background:"#f4f3fb",borderRadius:7,border:"1px solid #e0dcf3"}}>
      <b style={{color:"#5b4fc4"}}>{en?"Only normal days:":"Só dias normais:"}</b>{" "}
      {clean.groups[0].label} {clean.primary==="wake"?_rpHHMM(clean.groups[0].wakeMin):clean.primary==="wakings"?clean.groups[0].wakings:fmtDur(clean.groups[0].nightMin)}
      {" (n="+clean.groups[0].n+") · "}
      {clean.groups[1].label} {clean.primary==="wake"?_rpHHMM(clean.groups[1].wakeMin):clean.primary==="wakings"?clean.groups[1].wakings:fmtDur(clean.groups[1].nightMin)}
      {" (n="+clean.groups[1].n+")"}
    </div>}
    </div>);
  };
  // v11.9.141: noites atípicas (achado: 1 noite curtíssima ou que começou tarde demais puxa
  // a média do mês inteiro pra baixo). Critério literal pedido: <6h OU início ≥23h. KPI
  // mostra as 2 médias lado a lado só quando existe outlier de fato (senão são iguais e a
  // linha extra só ocupa espaço à toa).
  const withNClean=withN.filter(r=>!r.nightOutlier);
  const outlierCount=withN.length-withNClean.length;
  // v11.9.141: tendência de despertares em 7 dias — compara a média móvel de HOJE com a de
  // 7 dias atrás (mesma métrica, 2 pontos), pra ver direção sem o ruído dia-a-dia.
  const maNow=rep.rows[rep.rows.length-1]?.wakingsMA7;
  const maPrior=rep.rows[rep.rows.length-8]?.wakingsMA7;
  const th={textAlign:"right",fontSize:8,textTransform:"uppercase",letterSpacing:.4,color:"#7b80a0",borderBottom:"1.5px solid #d8dae8",padding:"5px 4px",fontWeight:700,whiteSpace:"nowrap"};
  const td={padding:"4px",borderBottom:"1px solid #eff0f6",color:"#3a3d60",textAlign:"right",whiteSpace:"nowrap"};
  return(<div id="lp-report" className="page-switch" style={{position:"fixed",inset:0,zIndex:250,background:"#eceef5",overflowY:"auto",overflowX:"hidden",overscrollBehavior:"none",WebkitOverflowScrolling:"touch",paddingTop:"env(safe-area-inset-top)",paddingBottom:"calc(40px + env(safe-area-inset-bottom))"}}>
    {/* barra de ações — some na impressão */}
    <div className="no-print" style={{position:"sticky",top:0,zIndex:2,display:"flex",alignItems:"center",gap:8,padding:"12px 14px",background:"rgba(236,238,245,0.94)",backdropFilter:"blur(10px)",borderBottom:"1px solid #dcdee9"}}>
      <button className="hit44" onClick={onBack} aria-label={en?"Back":"Voltar"} style={{width:34,height:34,borderRadius:10,background:"#fff",border:"1px solid #d8dae8",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0,color:"#4a4f70"}}>
        <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"><path d="M19 12H5"/><path d="M12 19l-7-7 7-7"/></svg>
      </button>
      <div style={{flex:1,minWidth:0,fontSize:13,fontWeight:700,color:"#23263f",letterSpacing:-.2}}>{en?"30-day report":"Relatório de 30 dias"}</div>
      <button onClick={onShare} style={{padding:"8px 12px",borderRadius:9,background:"#fff",border:"1px solid #d8dae8",fontSize:12,fontWeight:700,color:"#4a4f70",display:"flex",alignItems:"center",gap:5}}>
        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8"/><polyline points="16 6 12 2 8 6"/><line x1="12" y1="2" x2="12" y2="15"/></svg>
        {en?"Send":"Enviar"}
      </button>
      <button onClick={onSave} disabled={saving} style={{padding:"8px 12px",borderRadius:9,background:"#5b4fc4",border:"none",fontSize:12,fontWeight:700,color:"#fff",display:"flex",alignItems:"center",gap:5,opacity:saving?0.6:1}}>
        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
        {saving?(en?"Generating…":"Gerando…"):"PDF"}
      </button>
    </div>

    <div className="rep-paper" style={{background:"#fff",margin:"12px 10px 24px",borderRadius:8,padding:"22px 18px 24px",boxShadow:"0 6px 22px -10px rgba(20,22,50,.25)",fontFamily:"-apple-system,'Segoe UI',system-ui,sans-serif",color:"#23263f"}}>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-end",gap:10,borderBottom:"2px solid #5b4fc4",paddingBottom:11}}>
        <div style={{minWidth:0}}>
          <div style={{fontSize:19,fontWeight:700,letterSpacing:-.4}}>{(babyName||"Louise")+(en?" · Sleep & routine":" · Sono e rotina")}</div>
          <div style={{fontSize:11.5,color:"#6b7090",marginTop:3}}>{dLong(rep.from)} {en?"to":"a"} {dLong(rep.to)} · 30 {en?"days":"dias"}</div>
        </div>
        <div style={{fontSize:10,color:"#8b90ad",textAlign:"right",lineHeight:1.5,flexShrink:0}}>
          {ageStr&&<>{en?"Age":"Idade"}: {ageStr}<br/></>}
          {en?"Generated by Louise Pro":"Gerado pelo Louise Pro"}
        </div>
      </div>

      <div style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:9,margin:"16px 0 6px"}}>
        <K k={en?"Night sleep":"Sono noturno"} v={fmtDur(avg(withN,r=>r.night.durationMin))} s={(en?"real ":"real ")+fmtDur(avg(withN,r=>r.night.realMin))+" · "+avg1(withN,r=>r.night.wakings)+(en?" wakings":" despertares")}
          extra={<>
            {outlierCount>0&&<div style={{fontSize:9.5,color:"#a3792e",marginTop:3,fontWeight:600}}>{en?`Excl. ${outlierCount} outlier${outlierCount>1?"s":""}: ${fmtDur(avg(withNClean,r=>r.night.durationMin))}`:`Sem ${outlierCount} atípica${outlierCount>1?"s":""}: ${fmtDur(avg(withNClean,r=>r.night.durationMin))}`}</div>}
            {/* v11.9.144: a média só das noites SEM contexto marcado — separa "dormiu
                diferente" de "dormiu diferente PORQUE tomou vacina ontem". */}
            {tagged.length>0&&cleanN.length>=3&&<div style={{fontSize:9.5,color:"#5b4fc4",marginTop:2,fontWeight:600}}>{en?`Only normal days (${cleanN.length}): ${fmtDur(avg(cleanN,r=>r.night.durationMin))} · ${avg1(cleanN,r=>r.night.wakings)} wak.`:`Só dias normais (${cleanN.length}): ${fmtDur(avg(cleanN,r=>r.night.durationMin))} · ${avg1(cleanN,r=>r.night.wakings)} desp.`}</div>}
          </>}/>
        <K k={en?"Naps":"Sonecas"} v={avg1(withNap,r=>r.napCount)+(en?"/day":"/dia")} s={fmtDur(avg(withNap,r=>r.napTotalMin))+(en?" total":" no total")}
          extra={withFN.length?<div style={{fontSize:9.5,color:"#5b4fc4",marginTop:3,fontWeight:600}}>{en?`1st nap: ${fmtDur(avg(withFN,r=>r.firstNapMin))} avg`:`1ª soneca: ${fmtDur(avg(withFN,r=>r.firstNapMin))} de média`}</div>:null}/>
        <K k={en?"Awake window":"Janela acordada"} v={fmtDur(avg(withW,r=>r.maxWindowMin))} s={en?"longest of the day (avg)":"maior do dia (média)"}/>
        <K k={en?"Feeds":"Mamadas"} v={avg1(withF,r=>r.feedCount)+(en?"/day":"/dia")} s={avg(withF,r=>r.mlTotal)+(en?"ml per day":"ml por dia")}/>
      </div>
      {/* v11.9.141: tendência de 7 dias dos despertares — pedido explícito ("ver sem ruído
          diário"), 2 pontos (agora vs 7 dias atrás) em vez de gráfico novo. */}
      {maNow!=null&&maPrior!=null&&<div style={{fontSize:10.5,color:"#5a5f80",margin:"0 0 4px",padding:"7px 10px",background:"#f7f7fc",borderRadius:7,border:"1px solid #e8e9f2"}}>
        {en?"Wakings trend (7d avg): ":"Tendência de despertares (média 7d): "}
        <b style={{color:"#2d2f57"}}>{maNow.toFixed(1)}/{en?"night":"noite"}</b>
        {" "}{maNow<maPrior?(en?"↓ down from ":"↓ caindo de "):maNow>maPrior?(en?"↑ up from ":"↑ subindo de "):(en?"· same as ":"· igual a ")}
        {maPrior.toFixed(1)} {en?"7 days ago":"há 7 dias"}
      </div>}

      <div style={{fontSize:12.5,fontWeight:700,margin:"20px 0 5px",letterSpacing:-.2}}>{en?"30-day map":"Mapa dos 30 dias"}</div>
      <div style={{display:"flex",flexWrap:"wrap",gap:11,fontSize:10,color:"#5a5f80",marginBottom:8,alignItems:"center"}}>
        {[[en?"Night sleep":"Sono noturno","#4c4f8f",15],[en?"Nap":"Soneca","#9b8df8",15],[en?"Awake":"Acordada","#f4f5fa",15],[en?"Feed":"Mamada","#e08a1e",2.5]].map((l,i)=>
          <span key={i} style={{display:"inline-flex",alignItems:"center",gap:5}}><i style={{display:"inline-block",width:l[2],height:9,borderRadius:2,background:l[1],border:l[1]==="#f4f5fa"?"1px solid #e2e3ef":"none"}}/>{l[0]}</span>)}
      </div>
      <div style={{position:"relative",height:12,marginLeft:56}}>
        {[0,6,12,18,24].map(h=><span key={h} style={{position:"absolute",left:pc(h*60),transform:h===0?"none":h===24?"translateX(-100%)":"translateX(-50%)",fontSize:8.5,color:"#9a9fbb"}}>{String(h).padStart(2,"0")}h</span>)}
      </div>
      {rows.map(r=><div key={r.date} style={{display:"flex",alignItems:"center",height:13}}>
        <span style={{width:56,fontSize:8.5,color:"#7b80a0",fontVariantNumeric:"tabular-nums",flexShrink:0}}>{_rpWd(r.date,en)} {dShort(r.date)}</span>
        <div style={{position:"relative",flex:1,height:10,background:"#f4f5fa",borderRadius:2,backgroundImage:"repeating-linear-gradient(to right,#e6e7f1 0 1px,transparent 1px 12.5%)"}}>
          {r.sleepSegs.map((s,i)=><i key={"s"+i} style={{position:"absolute",top:0,height:10,borderRadius:2,background:"#4c4f8f",left:pc(s.from),width:pc(s.to-s.from)}}/>)}
          {r.napSegs.map((s,i)=><i key={"n"+i} style={{position:"absolute",top:0,height:10,borderRadius:2,background:"#9b8df8",left:pc(s.from),width:pc(s.to-s.from)}}/>)}
          {r.feedMins.map((m,i)=><i key={"f"+i} style={{position:"absolute",top:-3,width:1.5,height:4,background:"#e08a1e",borderRadius:1,left:pc(m)}}/>)}
        </div>
      </div>)}

      <div style={{fontSize:12.5,fontWeight:700,margin:"20px 0 4px",letterSpacing:-.2}}>{en?"Day by day":"Dia a dia"}</div>
      <div style={{fontSize:10,color:"#7b80a0",marginBottom:8,lineHeight:1.5}}>{en?"Real sleep = night duration minus time awake during wakings. Window = longest awake stretch between naps. Pre-sleep window = the one right before bedtime. * = atypical night (<6h or started ≥23h), excluded from the \"excl. outliers\" average above.":"Sono real = duração da noite menos o tempo acordada nos despertares. Janela = maior período acordada entre uma soneca e outra. Janela pré-sono = a que vem logo antes do bedtime. * = noite atípica (<6h ou começou às 23h+), excluída da média \"sem atípicas\" acima."}</div>
      <div className="rep-scroll" style={{overflowX:"auto",WebkitOverflowScrolling:"touch"}}>
        <table style={{width:"100%",minWidth:900,borderCollapse:"collapse",fontSize:9.5,fontVariantNumeric:"tabular-nums"}}>
          <thead><tr>
            <th style={{...th,textAlign:"left"}}>{en?"Day":"Dia"}</th>
            <th style={{...th,textAlign:"left"}}>{en?"Woke":"Acordou"}</th>
            <th style={{...th,textAlign:"left"}}>{en?"Night":"Noite"}</th>
            <th style={th}>{en?"Duration":"Duração"}</th>
            <th style={th}>{en?"Wak.":"Desp."}</th>
            <th style={th}>{en?"Wak. (min)":"Desp. (min)"}</th>
            <th style={th}>{en?"Real":"Sono real"}</th>
            <th style={th}>{en?"Day total":"Sono total"}</th>
            <th style={th}>{en?"Naps":"Sonecas"}</th>
            <th style={th}>{en?"Total":"Total"}</th>
            <th style={th}>{en?"1st nap":"1ª soneca"}</th>
            <th style={th}>{en?"Naps (min)":"Sonecas (min)"}</th>
            <th style={th}>{en?"Window":"Maior janela"}</th>
            <th style={th}>{en?"Pre-sleep":"Pré-sono"}</th>
            <th style={th}>{en?"Feeds":"Mamadas"}</th>
            <th style={th}>{en?"Milk":"Leite"}</th>
            <th style={{...th,textAlign:"left"}}>{en?"Context":"Contexto"}</th>
          </tr></thead>
          <tbody>{rows.map((r,i)=><tr key={r.date} style={r.partial?{background:"#f3f2fb",opacity:.72}:(i%2?{background:"#fafaff"}:null)}>
            <td style={{...td,textAlign:"left",fontWeight:600,color:"#23263f"}}>{_rpWd(r.date,en)} {dShort(r.date)}
              {/* v11.9.144: hoje ainda está acontecendo — marcado e fora de todas as médias */}
              {r.partial&&<span style={{fontSize:8,fontWeight:800,color:"#5b4fc4",marginLeft:4,letterSpacing:.4}}>{en?"PARTIAL":"PARCIAL"}</span>}</td>
            <td style={{...td,textAlign:"left"}}>{r.wake||"—"}</td>
            <td style={{...td,textAlign:"left"}}>{r.night?r.night.start+"→"+r.night.end:"—"}</td>
            <td style={td}>{r.night?fmtDur(r.night.durationMin):"—"}{r.nightOutlier&&<span style={{color:"#c2872b",fontWeight:800}}>{" *"}</span>}</td>
            <td style={td}>{r.night?r.night.wakings:"—"}</td>
            <td style={td}>{r.wakingDurations.length?r.wakingDurations.join(","):"—"}</td>
            <td style={td}>{r.night?fmtDur(r.night.realMin):"—"}</td>
            <td style={td}>{r.totalSleepMin?fmtDur(r.totalSleepMin):"—"}</td>
            <td style={td}>{r.napCount||"—"}</td>
            <td style={td}>{r.napTotalMin?fmtDur(r.napTotalMin):"—"}</td>
            <td style={td}>{r.firstNapMin?<span>{fmtDur(r.firstNapMin)}<span style={{color:"#a0a5bd"}}> ·{r.firstNapStart}</span></span>:"—"}</td>
            <td style={td}>{r.napDurations.length?r.napDurations.join(","):"—"}</td>
            <td style={td}>{r.maxWindowMin?fmtDur(r.maxWindowMin):"—"}</td>
            <td style={td}>{r.preBedWindowMin?fmtDur(r.preBedWindowMin):"—"}</td>
            <td style={td}>{r.feedCount||"—"}</td>
            <td style={td}>{r.mlTotal?r.mlTotal+"ml":"—"}</td>
            <td style={{...td,textAlign:"left",whiteSpace:"nowrap"}}>{r.tags&&r.tags.length
              ?r.tags.map(k=>EVENT_TAGS[k]?EVENT_TAGS[k].emoji:"").join(" ")
              :<span style={{color:"#c9ccdb"}}>—</span>}</td>
          </tr>)}</tbody>
        </table>
      </div>

      {/* v11.9.144: legenda das tags — sem isso os emojis da coluna Contexto não significam
          nada pra quem recebe o relatório (a pediatra). Só aparece se houver tag registrada. */}
      {tagged.length>0&&<div style={{marginTop:9,padding:"9px 11px",background:"#f7f7fc",border:"1px solid #e8e9f2",borderRadius:8,fontSize:9.5,color:"#5a5f80",lineHeight:1.6}}>
        <b style={{color:"#23263f"}}>{en?"Context: ":"Contexto: "}</b>
        {Object.keys(EVENT_TAGS).map(k=>`${EVENT_TAGS[k].emoji} ${en?EVENT_TAGS[k].en:EVENT_TAGS[k].pt}`).join(" · ")}
        <div style={{marginTop:3,fontStyle:"italic",color:"#8b90ad"}}>
          {en?"Vaccine and new food also mark the following days, since reactions usually show up later.":"Vacina e alimento novo marcam também os dias seguintes, já que a reação costuma aparecer depois."}
        </div>
      </div>}

      {/* v11.9.142: comparações — só na tela (não no PDF), mesmo raciocínio de escopo da
          tendência de 7d: útil pros pais investigarem, não é o tipo de coisa que precisa ir
          pro documento estático da pediatra. Renomeado de "Correlações" pra "Comparações"
          na revisão Opus+Fable — o que é mostrado é diferença descritiva de médias entre 2
          grupos, não correlação estatística de verdade (que exigiria expor r/p-valor). */}
      <div style={{fontSize:12.5,fontWeight:700,margin:"20px 0 4px",letterSpacing:-.2}}>{en?"Comparisons":"Comparações"}</div>
      <div style={{fontSize:9.5,color:"#8b90ad",marginBottom:10,lineHeight:1.5,fontStyle:"italic"}}>{en?"Descriptive comparisons, not proof of cause and effect. Louise changes over the month itself, so groups may reflect different weeks, not the effect of the variable. \"n\" = how many days support each average.":"Comparações descritivas — não provam causa e efeito. A Louise muda ao longo do próprio mês, então os grupos podem refletir semanas diferentes, não o efeito da variável. \"n\" = quantos dias sustentam cada média."}</div>
      <Corr title={en?"Naps: 3 vs 4 → the following night's sleep":"Sonecas: 3 vs 4 → o sono da noite seguinte"} data={corr.naps} clean={corrClean.naps} showNapAvg/>
      <Corr title={en?"Awake window before bed → same night's wakings":"Janela acordada antes de dormir → despertares da mesma noite"} data={corr.preBedWindow} clean={corrClean.preBedWindow}/>
      {corr.milk&&<Corr title={en?`Daily milk (split at ${corr.milk.medianMl}ml median) → wakings that night`:`Leite do dia (corte na mediana, ${corr.milk.medianMl}ml) → despertares daquela noite`} data={corr.milk} clean={corrClean.milk}/>}
      <Corr title={en?"Bedtime before/after 19:30 → wake-up time":"Bedtime antes/depois de 19h30 → horário de acordar"} data={corr.bedtime} clean={corrClean.bedtime}/>

      <div style={{marginTop:14,paddingTop:9,borderTop:"1px solid #e8e9f2",fontSize:9.5,color:"#8b90ad",lineHeight:1.5}}>
        {en?"Entries logged manually by the parents in the Louise Pro app — unlogged periods show as awake on the map. Tracking document; does not replace professional evaluation.":"Registros feitos manualmente pelos pais no app Louise Pro — períodos não registrados aparecem como acordada no mapa. Documento de acompanhamento, não substitui avaliação profissional."}
      </div>
    </div>
  </div>);
});
