// ── RELATÓRIO DE 30 DIAS · página-documento (v11.9.136) ──
// Aprovado do mockup `.claude/mockups/relatorio-30d.html`. Três blocos: médias, MAPA dos 30
// dias (actograma — cada linha é um dia das 00h às 24h) e tabela dia a dia.
// ⚠️ Paleta CLARA de propósito: isto é um DOCUMENTO pra imprimir/enviar à pediatra, não uma
// tela do app — por isso não usa os tokens escuros do `T` nem a escala tipográfica da UI
// (usa a escala do documento). É a única tela do app assim, e é intencional.
//
// v11.9.137: ⚠️ window.print() é NO-OP em PWA standalone no iOS (mesma família da landmine
// dos haptics) — o William confirmou no device. O botão "Salvar" agora RENDERIZA O DOCUMENTO
// NUM CANVAS (função abaixo, zero dependência) e entrega o PNG pro share sheet nativo, que
// funciona no standalone: WhatsApp, Salvar em Arquivos e Imprimir saem todos dali.
// window.print() ficou só como fallback de desktop (onde funciona e gera PDF real).

// Desenha o relatório inteiro num canvas 2x (data-driven a partir do `rep` — não lê o DOM).
// Layout espelha a página: cabeçalho, 4 KPIs, mapa (actograma), tabela 11 colunas, rodapé.
function renderReportCanvas(rep,opts){
  const en=opts.lang==="en";
  const loc=en?"en-US":"pt-BR";
  const dShort=d=>new Date(d+"T12:00:00").toLocaleDateString(loc,{day:"2-digit",month:"2-digit"});
  const dLong=d=>new Date(d+"T12:00:00").toLocaleDateString(loc,{day:"numeric",month:"long"});
  const rows=rep.rows.slice().reverse();
  const withN=rep.rows.filter(r=>r.night),withNap=rep.rows.filter(r=>r.napCount>0),
        withF=rep.rows.filter(r=>r.feedCount>0),withW=rep.rows.filter(r=>r.maxWindowMin>0);
  const avg=(a,f)=>a.length?Math.round(a.reduce((s,x)=>s+f(x),0)/a.length):0;
  const avg1=(a,f)=>a.length?(a.reduce((s,x)=>s+f(x),0)/a.length).toFixed(1).replace(".",en?".":","):"0";
  const S=2,W=780,PAD=28;
  const mapRowH=13,tblRowH=13.5;
  const mapY=224,mapH=rows.length*mapRowH;
  const tblTitleY=mapY+mapH+30,theadY=tblTitleY+32,tbodyY=theadY+14;
  const footY=tbodyY+rows.length*tblRowH+16;
  const H=footY+44;
  const canvas=document.createElement("canvas");
  canvas.width=W*S;canvas.height=Math.ceil(H)*S;
  const ctx=canvas.getContext("2d");
  ctx.scale(S,S);
  const F=w=>`${w} -apple-system,'Segoe UI',system-ui,sans-serif`;
  const box=(x,y,w,h,r,fill,stroke)=>{ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x,y,w,h,r);else ctx.rect(x,y,w,h);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke()}};
  // fundo
  ctx.fillStyle="#ffffff";ctx.fillRect(0,0,W,H);
  // ── cabeçalho ──
  ctx.fillStyle="#23263f";ctx.font=F("700 20px");ctx.textBaseline="alphabetic";
  ctx.fillText((opts.babyName||"Louise")+(en?" · Sleep & routine":" · Sono e rotina"),PAD,44);
  ctx.fillStyle="#6b7090";ctx.font=F("400 11.5px");
  ctx.fillText(dLong(rep.from)+(en?" to ":" a ")+dLong(rep.to)+" · 30 "+(en?"days":"dias"),PAD,62);
  ctx.fillStyle="#8b90ad";ctx.font=F("400 10px");ctx.textAlign="right";
  let my=36;
  if(opts.ageStr){ctx.fillText((en?"Age: ":"Idade: ")+opts.ageStr,W-PAD,my);my+=14}
  if(opts.birthDate){ctx.fillText((en?"Born ":"Nascimento: ")+dLong(opts.birthDate)+(en?"":" de ")+new Date(opts.birthDate+"T12:00:00").getFullYear(),W-PAD,my);my+=14}
  ctx.fillText(en?"Generated by Louise Pro":"Gerado pelo Louise Pro",W-PAD,my);
  ctx.textAlign="left";
  ctx.fillStyle="#5b4fc4";ctx.fillRect(PAD,72,W-2*PAD,2.5);
  // ── KPIs ──
  const kw=(W-2*PAD-3*10)/4,ky=90;
  const kpis=[
    [en?"NIGHT SLEEP":"SONO NOTURNO",fmtDur(avg(withN,r=>r.night.durationMin)),(en?"real ":"real ")+fmtDur(avg(withN,r=>r.night.realMin))+" · "+avg1(withN,r=>r.night.wakings)+(en?" wakings":" despertares")],
    [en?"NAPS":"SONECAS",avg1(withNap,r=>r.napCount)+(en?"/day":"/dia"),fmtDur(avg(withNap,r=>r.napTotalMin))+(en?" total":" no total")],
    [en?"AWAKE WINDOW":"JANELA ACORDADA",fmtDur(avg(withW,r=>r.maxWindowMin)),en?"longest of the day (avg)":"maior do dia (média)"],
    [en?"FEEDS":"MAMADAS",avg1(withF,r=>r.feedCount)+(en?"/day":"/dia"),avg(withF,r=>r.mlTotal)+(en?"ml per day":"ml por dia")]
  ];
  kpis.forEach((k,i)=>{
    const x=PAD+i*(kw+10);
    box(x,ky,kw,64,8,"#fafaff","#e2e3ef");
    ctx.fillStyle="#7b80a0";ctx.font=F("700 8.5px");ctx.fillText(k[0],x+11,ky+18);
    ctx.fillStyle="#2d2f57";ctx.font=F("700 17px");ctx.fillText(k[1],x+11,ky+40);
    ctx.fillStyle="#7b80a0";ctx.font=F("400 9.5px");ctx.fillText(k[2],x+11,ky+55);
  });
  // ── mapa ──
  ctx.fillStyle="#23263f";ctx.font=F("700 12.5px");
  ctx.fillText(en?"30-day map":"Mapa dos 30 dias",PAD,182);
  // legenda
  let lx=PAD;const ly=192;
  const leg=[[en?"Night sleep":"Sono noturno","#4c4f8f",15],[en?"Nap":"Soneca","#9b8df8",15],[en?"Awake":"Acordada","#f4f5fa",15],[en?"Feed":"Mamada","#e08a1e",2.5]];
  ctx.font=F("400 9.5px");
  leg.forEach(l=>{
    ctx.fillStyle=l[1];ctx.fillRect(lx,ly,l[2],8);
    if(l[1]==="#f4f5fa"){ctx.strokeStyle="#e2e3ef";ctx.lineWidth=1;ctx.strokeRect(lx+0.5,ly+0.5,l[2]-1,7)}
    lx+=l[2]+5;ctx.fillStyle="#5a5f80";ctx.fillText(l[0],lx,ly+8);lx+=ctx.measureText(l[0]).width+13;
  });
  const tx0=PAD+56,tw=W-PAD-tx0;
  // eixo de horas
  ctx.fillStyle="#9a9fbb";ctx.font=F("400 8.5px");
  [0,6,12,18,24].forEach(h=>{
    const x=tx0+h/24*tw;
    ctx.textAlign=h===0?"left":h===24?"right":"center";
    ctx.fillText(String(h).padStart(2,"0")+"h",x,mapY-6);
  });
  ctx.textAlign="left";
  rows.forEach((r,i)=>{
    const y=mapY+i*mapRowH;
    ctx.fillStyle="#7b80a0";ctx.font=F("400 8.5px");
    ctx.fillText(_rpWd(r.date,en)+" "+dShort(r.date),PAD,y+8.5);
    ctx.fillStyle="#f4f5fa";ctx.fillRect(tx0,y,tw,10);
    ctx.fillStyle="#e6e7f1";for(let h=3;h<24;h+=3)ctx.fillRect(tx0+h/24*tw,y,1,10);
    ctx.fillStyle="#4c4f8f";r.sleepSegs.forEach(s=>ctx.fillRect(tx0+s.from/1440*tw,y,Math.max(1,(s.to-s.from)/1440*tw),10));
    ctx.fillStyle="#9b8df8";r.napSegs.forEach(s=>ctx.fillRect(tx0+s.from/1440*tw,y,Math.max(1,(s.to-s.from)/1440*tw),10));
    ctx.fillStyle="#e08a1e";r.feedMins.forEach(m=>ctx.fillRect(tx0+m/1440*tw,y-3,1.5,4));
  });
  // ── tabela ──
  ctx.fillStyle="#23263f";ctx.font=F("700 12.5px");
  ctx.fillText(en?"Day by day":"Dia a dia",PAD,tblTitleY);
  ctx.fillStyle="#7b80a0";ctx.font=F("400 9px");
  ctx.fillText(en?"Real sleep = night minus wakings. Window = longest awake stretch between naps.":"Sono real = noite menos os despertares. Janela = maior período acordada entre sonecas.",PAD,tblTitleY+14);
  const cols=[
    {x:PAD,a:"left",h:en?"DAY":"DIA",f:r=>_rpWd(r.date,en)+" "+dShort(r.date)},
    {x:96,a:"left",h:en?"WOKE":"ACORDOU",f:r=>r.wake||"—"},
    {x:150,a:"left",h:en?"NIGHT":"NOITE",f:r=>r.night?r.night.start+"→"+r.night.end:"—"},
    {x:330,a:"right",h:en?"DUR.":"DURAÇÃO",f:r=>r.night?fmtDur(r.night.durationMin):"—"},
    {x:372,a:"right",h:"DESP.",he:"WAK.",f:r=>r.night?String(r.night.wakings):"—"},
    {x:430,a:"right",h:en?"REAL":"SONO REAL",f:r=>r.night?fmtDur(r.night.realMin):"—"},
    {x:472,a:"right",h:en?"NAPS":"SONECAS",f:r=>r.napCount?String(r.napCount):"—"},
    {x:528,a:"right",h:"TOTAL",f:r=>r.napTotalMin?fmtDur(r.napTotalMin):"—"},
    {x:596,a:"right",h:en?"WINDOW":"JANELA",f:r=>r.maxWindowMin?fmtDur(r.maxWindowMin):"—"},
    {x:652,a:"right",h:en?"FEEDS":"MAMADAS",f:r=>r.feedCount?String(r.feedCount):"—"},
    {x:W-PAD,a:"right",h:en?"MILK":"LEITE",f:r=>r.mlTotal?r.mlTotal+"ml":"—"}
  ];
  ctx.font=F("700 8px");ctx.fillStyle="#7b80a0";
  cols.forEach(c=>{ctx.textAlign=c.a;ctx.fillText(en&&c.he?c.he:c.h,c.x,theadY)});
  ctx.fillStyle="#d8dae8";ctx.fillRect(PAD,theadY+4,W-2*PAD,1.5);
  rows.forEach((r,i)=>{
    const y=tbodyY+i*tblRowH;
    if(i%2){ctx.fillStyle="#fafaff";ctx.fillRect(PAD,y,W-2*PAD,tblRowH)}
    ctx.font=F("400 9px");
    cols.forEach((c,ci)=>{
      ctx.textAlign=c.a;
      ctx.fillStyle=ci===0?"#23263f":"#3a3d60";
      if(ci===0)ctx.font=F("600 9px");
      ctx.fillText(c.f(r),c.x,y+10);
      if(ci===0)ctx.font=F("400 9px");
    });
  });
  ctx.textAlign="left";
  // ── rodapé ──
  ctx.fillStyle="#e8e9f2";ctx.fillRect(PAD,footY,W-2*PAD,1);
  ctx.fillStyle="#8b90ad";ctx.font=F("400 9px");
  const foot=en
    ?["Entries logged manually by the parents in the Louise Pro app — unlogged periods show as awake on the map.","Tracking document; does not replace professional evaluation."]
    :["Registros feitos manualmente pelos pais no app Louise Pro — períodos não registrados aparecem como acordada no mapa.","Documento de acompanhamento, não substitui avaliação profissional."];
  ctx.fillText(foot[0],PAD,footY+15);
  ctx.fillText(foot[1],PAD,footY+28);
  return canvas;
}

// v11.9.138: PDF DE VERDADE, escrito à mão (zero dependência). O truque: PDF aceita JPEG
// embutido cru (filtro DCTDecode) — então o canvas do documento vira JPEG e este builder
// monta o arquivo binário em volta (catalog/pages/page/imagem/conteúdo + xref com offsets
// em bytes). Página única com o tamanho exato do documento (~190 DPI). O que quebra PDFs
// feitos à mão são os offsets do xref — o harness confere cada um contra a posição real.
function _reportPdfBytes(jpeg,imgW,imgH){
  const pageW=595.28,pageH=Math.round(pageW*imgH/imgW*100)/100;
  const te=new TextEncoder();
  const chunks=[];let offset=0;const xref=[];
  const put=u8=>{chunks.push(u8);offset+=u8.length};
  const puts=s=>put(te.encode(s));
  puts("%PDF-1.4\n");
  put(new Uint8Array([0x25,0xE2,0xE3,0xCF,0xD3,0x0A]));
  const mark=n=>{xref[n]=offset};
  mark(1);puts("1 0 obj\n<</Type/Catalog/Pages 2 0 R>>\nendobj\n");
  mark(2);puts("2 0 obj\n<</Type/Pages/Kids[3 0 R]/Count 1>>\nendobj\n");
  mark(3);puts("3 0 obj\n<</Type/Page/Parent 2 0 R/MediaBox[0 0 "+pageW+" "+pageH+"]/Resources<</XObject<</Im1 4 0 R>>/ProcSet[/PDF/ImageC]>>/Contents 5 0 R>>\nendobj\n");
  mark(4);puts("4 0 obj\n<</Type/XObject/Subtype/Image/Width "+imgW+"/Height "+imgH+"/ColorSpace/DeviceRGB/BitsPerComponent 8/Filter/DCTDecode/Length "+jpeg.length+">>\nstream\n");
  put(jpeg);puts("\nendstream\nendobj\n");
  const content="q\n"+pageW+" 0 0 "+pageH+" 0 0 cm\n/Im1 Do\nQ";
  mark(5);puts("5 0 obj\n<</Length "+content.length+">>\nstream\n"+content+"\nendstream\nendobj\n");
  const xrefStart=offset;
  let x="xref\n0 6\n0000000000 65535 f \n";
  for(let i=1;i<=5;i++)x+=String(xref[i]).padStart(10,"0")+" 00000 n \n";
  x+="trailer\n<</Size 6/Root 1 0 R>>\nstartxref\n"+xrefStart+"\n%%EOF";
  puts(x);
  const total=new Uint8Array(offset);let p=0;for(const c of chunks){total.set(c,p);p+=c.length}
  return total;
}
async function renderReportPDF(rep,opts){
  const canvas=renderReportCanvas(rep,opts);
  const jblob=await new Promise((res,rej)=>canvas.toBlob(b=>b?res(b):rej(new Error("toBlob falhou")),"image/jpeg",0.92));
  const jpeg=new Uint8Array(await jblob.arrayBuffer());
  return new Blob([_reportPdfBytes(jpeg,canvas.width,canvas.height)],{type:"application/pdf"});
}

const ReportPage = React.memo(function ReportPage({entries,birthDate,babyName,onBack,lang}){
  const en=lang==="en";
  const rep=useMemo(()=>sleepReport(entries,30),[entries]);
  const rows=rep.rows.slice().reverse();
  const withN=rep.rows.filter(r=>r.night),withNap=rep.rows.filter(r=>r.napCount>0),
        withF=rep.rows.filter(r=>r.feedCount>0),withW=rep.rows.filter(r=>r.maxWindowMin>0);
  const avg=(a,f)=>a.length?Math.round(a.reduce((s,x)=>s+f(x),0)/a.length):0;
  const avg1=(a,f)=>a.length?(a.reduce((s,x)=>s+f(x),0)/a.length).toFixed(1).replace(".",en?".":","):"0";
  const loc=en?"en-US":"pt-BR";
  const dShort=d=>new Date(d+"T12:00:00").toLocaleDateString(loc,{day:"2-digit",month:"2-digit"});
  const dLong=d=>new Date(d+"T12:00:00").toLocaleDateString(loc,{day:"numeric",month:"long"});
  const pc=m=>(m/1440*100).toFixed(2)+"%";
  let ageStr="";
  if(birthDate){const dd=Math.round((new Date(rep.to+"T12:00:00")-new Date(birthDate+"T12:00:00"))/864e5);
    const m=Math.floor(dd/30.4375),r=Math.round(dd-m*30.4375);
    ageStr=en?`${m} months and ${r} days`:`${m} meses e ${r} dias`}
  const onPrint=()=>{
    try{
      document.body.classList.add("print-report");
      const done=()=>{document.body.classList.remove("print-report");window.removeEventListener("afterprint",done)};
      window.addEventListener("afterprint",done);
      setTimeout(()=>{window.print();setTimeout(done,2000)},80);
    }catch(e){}
  };
  // v11.9.138: PDF DE VERDADE — canvas do documento → JPEG → arquivo .pdf montado à mão
  // (renderReportPDF acima). Share sheet com o .pdf no iOS (funciona no standalone);
  // fallback: download direto do arquivo (desktop). Nada depende de window.print.
  const[saving,setSaving]=useState(false);
  const onSave=async()=>{
    if(saving)return;setSaving(true);
    try{
      const blob=await renderReportPDF(rep,{lang,babyName,birthDate,ageStr});
      const fname=`${(babyName||"louise").toLowerCase().replace(/[^a-z0-9]/g,"")||"louise"}-30d-${todayStr()}.pdf`;
      const file=new File([blob],fname,{type:"application/pdf"});
      if(navigator.canShare&&navigator.canShare({files:[file]})){
        await navigator.share({files:[file],title:fname});
        Haptic.success();setSaving(false);return;
      }
      const url=URL.createObjectURL(blob);
      const a=document.createElement("a");a.href=url;a.download=fname;document.body.appendChild(a);a.click();
      setTimeout(()=>{document.body.removeChild(a);URL.revokeObjectURL(url)},1000);
      Haptic.success();
    }catch(e){/* AbortError = usuário fechou o share sheet */}
    setSaving(false);
  };
  const onShare=async()=>{
    try{
      const txt=sleepReportText(rep,lang,babyName);
      if(navigator.share)await navigator.share({title:en?"Sleep & routine report":"Relatório de sono e rotina",text:txt});
      else await navigator.clipboard.writeText(txt);
      Haptic.success();
    }catch(e){}
  };
  const K=({k,v,s})=><div style={{border:"1px solid #e2e3ef",borderRadius:8,padding:"10px 11px",background:"#fafaff"}}>
    <div style={{fontSize:9,fontWeight:700,letterSpacing:.6,textTransform:"uppercase",color:"#7b80a0"}}>{k}</div>
    <div style={{fontSize:18,fontWeight:700,letterSpacing:-.5,marginTop:3,color:"#2d2f57"}}>{v}</div>
    <div style={{fontSize:10,color:"#7b80a0",marginTop:1}}>{s}</div>
  </div>;
  const th={textAlign:"right",fontSize:8,textTransform:"uppercase",letterSpacing:.4,color:"#7b80a0",borderBottom:"1.5px solid #d8dae8",padding:"5px 4px",fontWeight:700,whiteSpace:"nowrap"};
  const td={padding:"4px",borderBottom:"1px solid #eff0f6",color:"#3a3d60",textAlign:"right",whiteSpace:"nowrap"};
  return(<div id="lp-report" className="page-switch" style={{position:"fixed",inset:0,zIndex:250,background:"#eceef5",overflowY:"auto",overflowX:"hidden",overscrollBehavior:"none",WebkitOverflowScrolling:"touch",paddingTop:"env(safe-area-inset-top)",paddingBottom:"calc(40px + env(safe-area-inset-bottom))"}}>
    {/* barra de ações — some na impressão */}
    <div className="no-print" style={{position:"sticky",top:0,zIndex:2,display:"flex",alignItems:"center",gap:8,padding:"12px 14px",background:"rgba(236,238,245,0.94)",backdropFilter:"blur(10px)",borderBottom:"1px solid #dcdee9"}}>
      <button className="hit44" onClick={onBack} aria-label={en?"Back":"Voltar"} style={{width:34,height:34,borderRadius:10,background:"#fff",border:"1px solid #d8dae8",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0,color:"#4a4f70"}}>
        <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"><path d="M19 12H5"/><path d="M12 19l-7-7 7-7"/></svg>
      </button>
      <div style={{flex:1,minWidth:0,fontSize:13,fontWeight:700,color:"#23263f",letterSpacing:-.2}}>{en?"30-day report":"Relatório de 30 dias"}</div>
      <button onClick={onShare} style={{padding:"8px 12px",borderRadius:9,background:"#fff",border:"1px solid #d8dae8",fontSize:12,fontWeight:700,color:"#4a4f70",display:"flex",alignItems:"center",gap:5}}>
        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8"/><polyline points="16 6 12 2 8 6"/><line x1="12" y1="2" x2="12" y2="15"/></svg>
        {en?"Send":"Enviar"}
      </button>
      <button onClick={onSave} disabled={saving} style={{padding:"8px 12px",borderRadius:9,background:"#5b4fc4",border:"none",fontSize:12,fontWeight:700,color:"#fff",display:"flex",alignItems:"center",gap:5,opacity:saving?0.6:1}}>
        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
        {saving?(en?"Generating…":"Gerando…"):"PDF"}
      </button>
    </div>

    <div className="rep-paper" style={{background:"#fff",margin:"12px 10px 24px",borderRadius:8,padding:"22px 18px 24px",boxShadow:"0 6px 22px -10px rgba(20,22,50,.25)",fontFamily:"-apple-system,'Segoe UI',system-ui,sans-serif",color:"#23263f"}}>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-end",gap:10,borderBottom:"2px solid #5b4fc4",paddingBottom:11}}>
        <div style={{minWidth:0}}>
          <div style={{fontSize:19,fontWeight:700,letterSpacing:-.4}}>{(babyName||"Louise")+(en?" · Sleep & routine":" · Sono e rotina")}</div>
          <div style={{fontSize:11.5,color:"#6b7090",marginTop:3}}>{dLong(rep.from)} {en?"to":"a"} {dLong(rep.to)} · 30 {en?"days":"dias"}</div>
        </div>
        <div style={{fontSize:10,color:"#8b90ad",textAlign:"right",lineHeight:1.5,flexShrink:0}}>
          {ageStr&&<>{en?"Age":"Idade"}: {ageStr}<br/></>}
          {en?"Generated by Louise Pro":"Gerado pelo Louise Pro"}
        </div>
      </div>

      <div style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:9,margin:"16px 0 6px"}}>
        <K k={en?"Night sleep":"Sono noturno"} v={fmtDur(avg(withN,r=>r.night.durationMin))} s={(en?"real ":"real ")+fmtDur(avg(withN,r=>r.night.realMin))+" · "+avg1(withN,r=>r.night.wakings)+(en?" wakings":" despertares")}/>
        <K k={en?"Naps":"Sonecas"} v={avg1(withNap,r=>r.napCount)+(en?"/day":"/dia")} s={fmtDur(avg(withNap,r=>r.napTotalMin))+(en?" total":" no total")}/>
        <K k={en?"Awake window":"Janela acordada"} v={fmtDur(avg(withW,r=>r.maxWindowMin))} s={en?"longest of the day (avg)":"maior do dia (média)"}/>
        <K k={en?"Feeds":"Mamadas"} v={avg1(withF,r=>r.feedCount)+(en?"/day":"/dia")} s={avg(withF,r=>r.mlTotal)+(en?"ml per day":"ml por dia")}/>
      </div>

      <div style={{fontSize:12.5,fontWeight:700,margin:"20px 0 5px",letterSpacing:-.2}}>{en?"30-day map":"Mapa dos 30 dias"}</div>
      <div style={{display:"flex",flexWrap:"wrap",gap:11,fontSize:10,color:"#5a5f80",marginBottom:8,alignItems:"center"}}>
        {[[en?"Night sleep":"Sono noturno","#4c4f8f",15],[en?"Nap":"Soneca","#9b8df8",15],[en?"Awake":"Acordada","#f4f5fa",15],[en?"Feed":"Mamada","#e08a1e",2.5]].map((l,i)=>
          <span key={i} style={{display:"inline-flex",alignItems:"center",gap:5}}><i style={{display:"inline-block",width:l[2],height:9,borderRadius:2,background:l[1],border:l[1]==="#f4f5fa"?"1px solid #e2e3ef":"none"}}/>{l[0]}</span>)}
      </div>
      <div style={{position:"relative",height:12,marginLeft:56}}>
        {[0,6,12,18,24].map(h=><span key={h} style={{position:"absolute",left:pc(h*60),transform:h===0?"none":h===24?"translateX(-100%)":"translateX(-50%)",fontSize:8.5,color:"#9a9fbb"}}>{String(h).padStart(2,"0")}h</span>)}
      </div>
      {rows.map(r=><div key={r.date} style={{display:"flex",alignItems:"center",height:13}}>
        <span style={{width:56,fontSize:8.5,color:"#7b80a0",fontVariantNumeric:"tabular-nums",flexShrink:0}}>{_rpWd(r.date,en)} {dShort(r.date)}</span>
        <div style={{position:"relative",flex:1,height:10,background:"#f4f5fa",borderRadius:2,backgroundImage:"repeating-linear-gradient(to right,#e6e7f1 0 1px,transparent 1px 12.5%)"}}>
          {r.sleepSegs.map((s,i)=><i key={"s"+i} style={{position:"absolute",top:0,height:10,borderRadius:2,background:"#4c4f8f",left:pc(s.from),width:pc(s.to-s.from)}}/>)}
          {r.napSegs.map((s,i)=><i key={"n"+i} style={{position:"absolute",top:0,height:10,borderRadius:2,background:"#9b8df8",left:pc(s.from),width:pc(s.to-s.from)}}/>)}
          {r.feedMins.map((m,i)=><i key={"f"+i} style={{position:"absolute",top:-3,width:1.5,height:4,background:"#e08a1e",borderRadius:1,left:pc(m)}}/>)}
        </div>
      </div>)}

      <div style={{fontSize:12.5,fontWeight:700,margin:"20px 0 4px",letterSpacing:-.2}}>{en?"Day by day":"Dia a dia"}</div>
      <div style={{fontSize:10,color:"#7b80a0",marginBottom:8,lineHeight:1.5}}>{en?"Real sleep = night duration minus time awake during wakings. Window = longest awake stretch between naps.":"Sono real = duração da noite menos o tempo acordada nos despertares. Janela = maior período acordada entre uma soneca e outra."}</div>
      <div className="rep-scroll" style={{overflowX:"auto",WebkitOverflowScrolling:"touch"}}>
        <table style={{width:"100%",minWidth:600,borderCollapse:"collapse",fontSize:9.5,fontVariantNumeric:"tabular-nums"}}>
          <thead><tr>
            <th style={{...th,textAlign:"left"}}>{en?"Day":"Dia"}</th>
            <th style={{...th,textAlign:"left"}}>{en?"Woke":"Acordou"}</th>
            <th style={{...th,textAlign:"left"}}>{en?"Night":"Noite"}</th>
            <th style={th}>{en?"Duration":"Duração"}</th>
            <th style={th}>{en?"Wak.":"Desp."}</th>
            <th style={th}>{en?"Real":"Sono real"}</th>
            <th style={th}>{en?"Naps":"Sonecas"}</th>
            <th style={th}>{en?"Total":"Total"}</th>
            <th style={th}>{en?"Window":"Maior janela"}</th>
            <th style={th}>{en?"Feeds":"Mamadas"}</th>
            <th style={th}>{en?"Milk":"Leite"}</th>
          </tr></thead>
          <tbody>{rows.map((r,i)=><tr key={r.date} style={i%2?{background:"#fafaff"}:null}>
            <td style={{...td,textAlign:"left",fontWeight:600,color:"#23263f"}}>{_rpWd(r.date,en)} {dShort(r.date)}</td>
            <td style={{...td,textAlign:"left"}}>{r.wake||"—"}</td>
            <td style={{...td,textAlign:"left"}}>{r.night?r.night.start+"→"+r.night.end:"—"}</td>
            <td style={td}>{r.night?fmtDur(r.night.durationMin):"—"}</td>
            <td style={td}>{r.night?r.night.wakings:"—"}</td>
            <td style={td}>{r.night?fmtDur(r.night.realMin):"—"}</td>
            <td style={td}>{r.napCount||"—"}</td>
            <td style={td}>{r.napTotalMin?fmtDur(r.napTotalMin):"—"}</td>
            <td style={td}>{r.maxWindowMin?fmtDur(r.maxWindowMin):"—"}</td>
            <td style={td}>{r.feedCount||"—"}</td>
            <td style={td}>{r.mlTotal?r.mlTotal+"ml":"—"}</td>
          </tr>)}</tbody>
        </table>
      </div>

      <div style={{marginTop:14,paddingTop:9,borderTop:"1px solid #e8e9f2",fontSize:9.5,color:"#8b90ad",lineHeight:1.5}}>
        {en?"Entries logged manually by the parents in the Louise Pro app — unlogged periods show as awake on the map. Tracking document; does not replace professional evaluation.":"Registros feitos manualmente pelos pais no app Louise Pro — períodos não registrados aparecem como acordada no mapa. Documento de acompanhamento, não substitui avaliação profissional."}
      </div>
    </div>
  </div>);
});
